<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="Seq_2" Id="{4e6711ea-ed1c-4254-8be6-d45b1ea5b2a6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Seq_2
VAR_INPUT
	// Basis-Inputs
	bExecute			:BOOL;				// Trigger für Ausführung von Sequenz
	iSysCommand			:eSystemCommand;	// Steuerungsvariabel von System (Resetten)
	iSysState			:eSystemState;		// Information über Zustand von System
	
	
	// Prozess-Inputs 
	Position_1			:sRoboterProzessVariablen;
	Position_DOWN		:sRoboterProzessVariablen;
	Position_UP			:sRoboterProzessVariablen;
	Position_2			:sRoboterProzessVariablen;
END_VAR
VAR_OUTPUT
	bDone				:BOOL;				// Information ob Sequenz ausgfeührt wurde
	bBusy				:BOOL;				// Information ob Sequenz im Moment ausgeführt wird
	bError				:BOOL;				// Information ob sich Sequenz in Fehlerzustand befindet
END_VAR
VAR
	// Sequenz-Zustände
	iState				:eSequenceState;
	
	// Startvariablen (FB soll nur bei einer steigenden Flanke gestartet werden)
	fTrigger			:R_TRIG;			// Erkennung einer steigenden Flanke für den Starte
	fSwitch				:SR;				// Setzen des Signals
	bSwitchResett		:BOOL;				// Resetten des Signals
	
	// Zustandsvariablen
	bStarten			:BOOL;
	bStoppen			:BOOL;
	bResetten			:BOOL;
	
	// Management-Variablen:
	bFinished			:BOOL;
	bInit				:BOOL;
	
	// Skill-Instanziierungen
	P2P_Bewegung		:Skill_Position_anfahren;
	Position			:sRoboterProzessVariablen;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Aufrufen von Skills und Ablauf
Ablauf();	
Skills();

//_______________________________________________________________
// Reaktion auf Fehler
IF bError THEN
	iState := 3;
END_IF	

// Reaktion auf Input-Variablen: 
	// Starten
	fTrigger(CLK := bExecute);
	fSwitch(Set1 := fTrigger.Q);
	
	IF fSwitch.Q1 THEN
		bStarten := TRUE;
	ELSE
		bStarten := FALSE;
	END_IF
	
	// Stoppen
	IF iSysCommand = 3 THEN
		bStoppen := TRUE;	
	ELSE 
		bStoppen := FALSE;	
	END_IF
	
	// Stoppen
	IF iSysCommand = 4 THEN
		bResetten := TRUE;	
	ELSE 
		bResetten := FALSE;	
	END_IF



//_______________________________________________________________
// Zustandsmanagement
CASE iState OF 
	0:	// BEREIT
			// DO	
			fSwitch.RESET := FALSE;
				
			// TRANSITION
			IF bStarten THEN
				fSwitch.RESET := TRUE;
				iState := 1;																							// Starten des Objektes 
			END_IF
	// ________________________________________________________________________________			
	1:	// LAUFEND
			// DO
			bBusy := TRUE;	

			IF bStoppen THEN
				SFCReset := TRUE;
				bBusy := FALSE;
			END_IF	
			
			// TRANSITION
			IF bFinished THEN
				bFinished := FALSE;
				bBusy := FALSE;
				iState := 2;
			END_IF
			
			IF bInit THEN
				bInit := FALSE;
				SFCReset := FALSE;
				iState := 0;
			END_IF

	// ________________________________________________________________________________					
	2:	// ABGESCHLOSSEN
			// DO
			bDone := TRUE;			
						
			// TRANSITION
			IF bDone THEN
				bDone := FALSE;
				iState := 0;
			END_IF
	// ________________________________________________________________________________					
	3:	// FEHLER
			// DO
			bDone := FALSE;
			bBusy := FALSE;
			
			// TRANSITION
			IF bResetten THEN
				bError := FALSE;
				iState := 0;
			END_IF
			
END_CASE]]></ST>
    </Implementation>
    <Folder Name="00_Hilfsaktionen" Id="{9551f1fd-3283-49a9-864c-07abdc518f41}" />
    <Folder Name="01_Zusweisung" Id="{9e099ea1-4c50-4b6b-80e4-3448498f579a}" />
    <Action Name="Ablauf" Id="{a51db42b-1e45-453f-ae91-17e0b4bf9c4f}">
      <Implementation>
        <SFC>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="SFCImplementationObject">
                <o n="Root" t="SFCSegment">
                  <o n="ElementList" t="SFCElementList">
                    <l2 n="InnerList">
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" cet="SFCActionAssociation">
                            <o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"bInit"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">198L</v>
                                  <v n="IdParent">197L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">199L</v>
                                  <v n="IdParent">197L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">200L</v>
                                  <v n="IdParent">197L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">201L</v>
                                  <v n="IdParent">197L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"P"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">202L</v>
                                  <v n="IdParent">197L</v>
                                </o>
                              </l2>
                              <v n="Id">197L</v>
                              <v n="IdParent">3L</v>
                            </o>
                          </l2>
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Init"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">4L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">5L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">6L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">7L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"TRUE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">8L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">9L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">10L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">11L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">12L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">13L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">14L</v>
                            <v n="IdParent">3L</v>
                          </o>
                        </l2>
                        <v n="Id">3L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Init__to__Move_1"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"bStarten"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">27L</v>
                            <v n="IdParent">26L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">28L</v>
                            <v n="IdParent">26L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">29L</v>
                            <v n="IdParent">26L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">30L</v>
                            <v n="IdParent">26L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">31L</v>
                            <v n="IdParent">26L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">32L</v>
                            <v n="IdParent">26L</v>
                          </o>
                        </l2>
                        <v n="Id">26L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" cet="SFCActionAssociation">
                            <o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"Zuweisung_1"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">171L</v>
                                  <v n="IdParent">170L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">172L</v>
                                  <v n="IdParent">170L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">173L</v>
                                  <v n="IdParent">170L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">174L</v>
                                  <v n="IdParent">170L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"N"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">175L</v>
                                  <v n="IdParent">170L</v>
                                </o>
                              </l2>
                              <v n="Id">170L</v>
                              <v n="IdParent">33L</v>
                            </o>
                            <o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"P2P_Bewegung.bExecute"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">204L</v>
                                  <v n="IdParent">203L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">205L</v>
                                  <v n="IdParent">203L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">206L</v>
                                  <v n="IdParent">203L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">207L</v>
                                  <v n="IdParent">203L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"N"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">208L</v>
                                  <v n="IdParent">203L</v>
                                </o>
                              </l2>
                              <v n="Id">203L</v>
                              <v n="IdParent">33L</v>
                            </o>
                          </l2>
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Move_1"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">34L</v>
                            <v n="IdParent">33L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">35L</v>
                            <v n="IdParent">33L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">36L</v>
                            <v n="IdParent">33L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">37L</v>
                            <v n="IdParent">33L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">38L</v>
                            <v n="IdParent">33L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">39L</v>
                            <v n="IdParent">33L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">40L</v>
                            <v n="IdParent">33L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">41L</v>
                            <v n="IdParent">33L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">42L</v>
                            <v n="IdParent">33L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">43L</v>
                            <v n="IdParent">33L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Deaktivieren"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">44L</v>
                            <v n="IdParent">33L</v>
                          </o>
                        </l2>
                        <v n="Id">33L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Move_1__to__Warten_1"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"P2P_Bewegung.bDone"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">46L</v>
                            <v n="IdParent">45L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">47L</v>
                            <v n="IdParent">45L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">48L</v>
                            <v n="IdParent">45L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">49L</v>
                            <v n="IdParent">45L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">50L</v>
                            <v n="IdParent">45L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">51L</v>
                            <v n="IdParent">45L</v>
                          </o>
                        </l2>
                        <v n="Id">45L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Warten_1"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">351L</v>
                            <v n="IdParent">350L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">352L</v>
                            <v n="IdParent">350L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">353L</v>
                            <v n="IdParent">350L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">354L</v>
                            <v n="IdParent">350L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">355L</v>
                            <v n="IdParent">350L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">356L</v>
                            <v n="IdParent">350L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">357L</v>
                            <v n="IdParent">350L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">358L</v>
                            <v n="IdParent">350L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">359L</v>
                            <v n="IdParent">350L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">360L</v>
                            <v n="IdParent">350L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">361L</v>
                            <v n="IdParent">350L</v>
                          </o>
                        </l2>
                        <v n="Id">350L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Warten_1__to__Move_2"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"NOT P2P_Bewegung.bExecute"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">363L</v>
                            <v n="IdParent">362L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">364L</v>
                            <v n="IdParent">362L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">365L</v>
                            <v n="IdParent">362L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">366L</v>
                            <v n="IdParent">362L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">367L</v>
                            <v n="IdParent">362L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">368L</v>
                            <v n="IdParent">362L</v>
                          </o>
                        </l2>
                        <v n="Id">362L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" cet="SFCActionAssociation">
                            <o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"Zuweisung_2"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">177L</v>
                                  <v n="IdParent">176L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">178L</v>
                                  <v n="IdParent">176L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">179L</v>
                                  <v n="IdParent">176L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">180L</v>
                                  <v n="IdParent">176L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"N"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">181L</v>
                                  <v n="IdParent">176L</v>
                                </o>
                              </l2>
                              <v n="Id">176L</v>
                              <v n="IdParent">52L</v>
                            </o>
                            <o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"P2P_Bewegung.bExecute"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">210L</v>
                                  <v n="IdParent">209L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">211L</v>
                                  <v n="IdParent">209L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">212L</v>
                                  <v n="IdParent">209L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">213L</v>
                                  <v n="IdParent">209L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"N"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">214L</v>
                                  <v n="IdParent">209L</v>
                                </o>
                              </l2>
                              <v n="Id">209L</v>
                              <v n="IdParent">52L</v>
                            </o>
                          </l2>
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Move_2"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">53L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">54L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">55L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">56L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">57L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">58L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">59L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">60L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">61L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">62L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Deaktivieren"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">63L</v>
                            <v n="IdParent">52L</v>
                          </o>
                        </l2>
                        <v n="Id">52L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Move_2__to__Warten_2"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"P2P_Bewegung.bDone"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">370L</v>
                            <v n="IdParent">369L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">371L</v>
                            <v n="IdParent">369L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">372L</v>
                            <v n="IdParent">369L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">373L</v>
                            <v n="IdParent">369L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">374L</v>
                            <v n="IdParent">369L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">375L</v>
                            <v n="IdParent">369L</v>
                          </o>
                        </l2>
                        <v n="Id">369L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Warten_2"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">377L</v>
                            <v n="IdParent">376L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">378L</v>
                            <v n="IdParent">376L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">379L</v>
                            <v n="IdParent">376L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">380L</v>
                            <v n="IdParent">376L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">381L</v>
                            <v n="IdParent">376L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">382L</v>
                            <v n="IdParent">376L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">383L</v>
                            <v n="IdParent">376L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">384L</v>
                            <v n="IdParent">376L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">385L</v>
                            <v n="IdParent">376L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">386L</v>
                            <v n="IdParent">376L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">387L</v>
                            <v n="IdParent">376L</v>
                          </o>
                        </l2>
                        <v n="Id">376L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Warten_2__to__Move_DOWN"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"NOT P2P_Bewegung.bExecute"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">84L</v>
                            <v n="IdParent">83L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">85L</v>
                            <v n="IdParent">83L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">86L</v>
                            <v n="IdParent">83L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">87L</v>
                            <v n="IdParent">83L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">88L</v>
                            <v n="IdParent">83L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">89L</v>
                            <v n="IdParent">83L</v>
                          </o>
                        </l2>
                        <v n="Id">83L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" cet="SFCActionAssociation">
                            <o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"Zuweisung_DOWN"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">183L</v>
                                  <v n="IdParent">182L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">184L</v>
                                  <v n="IdParent">182L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">185L</v>
                                  <v n="IdParent">182L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">186L</v>
                                  <v n="IdParent">182L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"N"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">187L</v>
                                  <v n="IdParent">182L</v>
                                </o>
                              </l2>
                              <v n="Id">182L</v>
                              <v n="IdParent">90L</v>
                            </o>
                            <o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"P2P_Bewegung.bExecute"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">216L</v>
                                  <v n="IdParent">215L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">217L</v>
                                  <v n="IdParent">215L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">218L</v>
                                  <v n="IdParent">215L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">219L</v>
                                  <v n="IdParent">215L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"N"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">220L</v>
                                  <v n="IdParent">215L</v>
                                </o>
                              </l2>
                              <v n="Id">215L</v>
                              <v n="IdParent">90L</v>
                            </o>
                          </l2>
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Move_DOWN"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">91L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">92L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">93L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">94L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">95L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">96L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">97L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">98L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">99L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">100L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Deaktivieren"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">101L</v>
                            <v n="IdParent">90L</v>
                          </o>
                        </l2>
                        <v n="Id">90L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Move_DOWN__to__Warten_3"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"P2P_Bewegung.bDone"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">389L</v>
                            <v n="IdParent">388L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">390L</v>
                            <v n="IdParent">388L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">391L</v>
                            <v n="IdParent">388L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">392L</v>
                            <v n="IdParent">388L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">393L</v>
                            <v n="IdParent">388L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">394L</v>
                            <v n="IdParent">388L</v>
                          </o>
                        </l2>
                        <v n="Id">388L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Warten_3"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">396L</v>
                            <v n="IdParent">395L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">397L</v>
                            <v n="IdParent">395L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">398L</v>
                            <v n="IdParent">395L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">399L</v>
                            <v n="IdParent">395L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">400L</v>
                            <v n="IdParent">395L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">401L</v>
                            <v n="IdParent">395L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">402L</v>
                            <v n="IdParent">395L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">403L</v>
                            <v n="IdParent">395L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">404L</v>
                            <v n="IdParent">395L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">405L</v>
                            <v n="IdParent">395L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">406L</v>
                            <v n="IdParent">395L</v>
                          </o>
                        </l2>
                        <v n="Id">395L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Warten_3__to__MOVE_UP"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"NOT P2P_Bewegung.bExecute"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">103L</v>
                            <v n="IdParent">102L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">104L</v>
                            <v n="IdParent">102L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">105L</v>
                            <v n="IdParent">102L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">106L</v>
                            <v n="IdParent">102L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">107L</v>
                            <v n="IdParent">102L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">108L</v>
                            <v n="IdParent">102L</v>
                          </o>
                        </l2>
                        <v n="Id">102L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" cet="SFCActionAssociation">
                            <o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"Zuweisung_UP"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">189L</v>
                                  <v n="IdParent">188L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">190L</v>
                                  <v n="IdParent">188L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">191L</v>
                                  <v n="IdParent">188L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">192L</v>
                                  <v n="IdParent">188L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"N"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">193L</v>
                                  <v n="IdParent">188L</v>
                                </o>
                              </l2>
                              <v n="Id">188L</v>
                              <v n="IdParent">109L</v>
                            </o>
                            <o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"P2P_Bewegung.bExecute"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">222L</v>
                                  <v n="IdParent">221L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">223L</v>
                                  <v n="IdParent">221L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">224L</v>
                                  <v n="IdParent">221L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">225L</v>
                                  <v n="IdParent">221L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"N"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">226L</v>
                                  <v n="IdParent">221L</v>
                                </o>
                              </l2>
                              <v n="Id">221L</v>
                              <v n="IdParent">109L</v>
                            </o>
                          </l2>
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"MOVE_UP"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">110L</v>
                            <v n="IdParent">109L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">111L</v>
                            <v n="IdParent">109L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">112L</v>
                            <v n="IdParent">109L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">113L</v>
                            <v n="IdParent">109L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">114L</v>
                            <v n="IdParent">109L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">115L</v>
                            <v n="IdParent">109L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">116L</v>
                            <v n="IdParent">109L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">117L</v>
                            <v n="IdParent">109L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">118L</v>
                            <v n="IdParent">109L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">119L</v>
                            <v n="IdParent">109L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Deaktivieren"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">120L</v>
                            <v n="IdParent">109L</v>
                          </o>
                        </l2>
                        <v n="Id">109L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"MOVE_UP__to__Warten_4"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"P2P_Bewegung.bDone"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">408L</v>
                            <v n="IdParent">407L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">409L</v>
                            <v n="IdParent">407L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">410L</v>
                            <v n="IdParent">407L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">411L</v>
                            <v n="IdParent">407L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">412L</v>
                            <v n="IdParent">407L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">413L</v>
                            <v n="IdParent">407L</v>
                          </o>
                        </l2>
                        <v n="Id">407L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Warten_4"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">415L</v>
                            <v n="IdParent">414L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">416L</v>
                            <v n="IdParent">414L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">417L</v>
                            <v n="IdParent">414L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">418L</v>
                            <v n="IdParent">414L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">419L</v>
                            <v n="IdParent">414L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">420L</v>
                            <v n="IdParent">414L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">421L</v>
                            <v n="IdParent">414L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">422L</v>
                            <v n="IdParent">414L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">423L</v>
                            <v n="IdParent">414L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">424L</v>
                            <v n="IdParent">414L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">425L</v>
                            <v n="IdParent">414L</v>
                          </o>
                        </l2>
                        <v n="Id">414L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Warten_4__to__Finished"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"NOT P2P_Bewegung.bExecute"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">65L</v>
                            <v n="IdParent">64L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">66L</v>
                            <v n="IdParent">64L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">67L</v>
                            <v n="IdParent">64L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">68L</v>
                            <v n="IdParent">64L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">69L</v>
                            <v n="IdParent">64L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">70L</v>
                            <v n="IdParent">64L</v>
                          </o>
                        </l2>
                        <v n="Id">64L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" cet="SFCActionAssociation">
                            <o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"bFinished"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">122L</v>
                                  <v n="IdParent">121L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">123L</v>
                                  <v n="IdParent">121L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">124L</v>
                                  <v n="IdParent">121L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">125L</v>
                                  <v n="IdParent">121L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"N"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">126L</v>
                                  <v n="IdParent">121L</v>
                                </o>
                              </l2>
                              <v n="Id">121L</v>
                              <v n="IdParent">71L</v>
                            </o>
                          </l2>
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Finished"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">72L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">73L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">74L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">75L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">76L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">77L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">78L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">79L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">80L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">81L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">82L</v>
                            <v n="IdParent">71L</v>
                          </o>
                        </l2>
                        <v n="Id">71L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Finished__to__Init"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"TRUE"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">16L</v>
                            <v n="IdParent">15L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">17L</v>
                            <v n="IdParent">15L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">18L</v>
                            <v n="IdParent">15L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">19L</v>
                            <v n="IdParent">15L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">20L</v>
                            <v n="IdParent">15L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">21L</v>
                            <v n="IdParent">15L</v>
                          </o>
                        </l2>
                        <v n="Id">15L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCJump">
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Init"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">23L</v>
                            <v n="IdParent">22L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">24L</v>
                            <v n="IdParent">22L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">25L</v>
                            <v n="IdParent">22L</v>
                          </o>
                        </l2>
                        <v n="Id">22L</v>
                        <v n="IdParent">2L</v>
                      </o>
                    </l2>
                  </o>
                  <l2 n="Attributes" cet="SFCAttribute">
                    <o>
                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                      <o n="Value" t="StringValue">
                        <v n="Value">""</v>
                        <v n="DefaultValue">""</v>
                      </o>
                      <v n="Id">194L</v>
                      <v n="IdParent">2L</v>
                    </o>
                    <o>
                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                      <o n="Value" t="StringValue">
                        <v n="Value">""</v>
                        <v n="DefaultValue">""</v>
                      </o>
                      <v n="Id">195L</v>
                      <v n="IdParent">2L</v>
                    </o>
                    <o>
                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                      <o n="Value" t="BoolValue">
                        <v n="Value">"FALSE"</v>
                        <v n="DefaultValue">"FALSE"</v>
                      </o>
                      <v n="Id">196L</v>
                      <v n="IdParent">2L</v>
                    </o>
                  </l2>
                  <v n="Id">2L</v>
                  <v n="IdParent">-1L</v>
                </o>
                <d2 n="Categories" ckt="Guid" cvt="SFCAttributeCategory">
                  <v>1c5c6e05-2bb7-4258-bcee-fd16a540c63c</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Identifier">"Specific"</v>
                    <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                    <v n="Description">"Element type specific properties"</v>
                  </o>
                  <v>20f0fc67-978d-438b-979f-eef294f34ee4</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Identifier">"Actions"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Action definitions"</v>
                  </o>
                  <v>6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Identifier">"Common"</v>
                    <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                    <v n="Description">"Common properties"</v>
                  </o>
                  <v>d336ba06-8a67-4e6b-9697-50f83ba6bdde</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                    <v n="Identifier">"Times"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Time definitions"</v>
                  </o>
                </d2>
                <d2 n="Attributes" ckt="Guid" cvt="SFCAttributeDescription">
                  <v>01580b27-6378-448b-8ecb-0e4b795b58d6</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">true</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                    <v n="Identifier">"Exclude"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Exclude this element from build"</v>
                  </o>
                  <v>23bdaa98-72ec-41f7-817b-9dede5697086</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                    <v n="Identifier">"Parallel"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Sets the branch to parallel mode"</v>
                  </o>
                  <v>38391c6d-6d4a-42f8-8ee7-9f45e5adafa8</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                    <v n="Identifier">"Name"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Name of the element"</v>
                  </o>
                  <v>62e1754b-7629-4e63-9cec-10ae0c536f1f</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                    <v n="Identifier">"Duplication"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Copies the implementation of step actions or transitions with the element. Otherwise, copies the reference to an existing implementation."</v>
                  </o>
                  <v>6844a48e-46c2-4cc8-a185-a478f3b99cc0</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                    <v n="Identifier">"InitStep"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Sets the step as the initial step"</v>
                  </o>
                  <v>700a583f-b4d4-43e4-8c14-629c7cd3bec8</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                    <v n="Identifier">"MainAction"</v>
                    <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Description">"Name of the action to be called if the step is active"</v>
                  </o>
                  <v>7d894980-aeea-405c-a0f6-e2b26429c58f</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">true</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                    <v n="Identifier">"Comment"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Comment of the element"</v>
                  </o>
                  <v>8294df19-5962-4dee-a874-1051dabb0e3e</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                    <v n="Identifier">"Monitoring"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Indicates transition monitoring setting."</v>
                  </o>
                  <v>a2621e18-7de3-4ea6-ae6d-89e9e0b7befd</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                    <v n="Identifier">"ExitAction"</v>
                    <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Description">"Name of the action to be called if the step is deactivated"</v>
                  </o>
                  <v>a6b08bd8-b696-47e3-9cbf-7408b61c9ff8</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                    <v n="Identifier">"EntryAction"</v>
                    <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Description">"Name of the action to be called if the step is activated"</v>
                  </o>
                  <v>b693554c-1b01-4a8d-afde-9e3a46f7465d</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                    <v n="Identifier">"MaxTime"</v>
                    <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                    <v n="Description">"Defines the maximal active time for the step"</v>
                  </o>
                  <v>bc882c11-1e91-4dd8-a6b8-2075724ed18b</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                    <v n="Identifier">"Symbol"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Symbol configuration setting of the element"</v>
                  </o>
                  <v>cacf1a68-236e-47c2-b7b1-1cf9199718cb</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                    <v n="Identifier">"MinTime"</v>
                    <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                    <v n="Description">"Defines the minimal active time for the step"</v>
                  </o>
                  <v>e174fc0d-80b0-4a9e-a530-ca239c249a50</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                    <v n="Identifier">"Qualifier"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Qualifier of the action association"</v>
                  </o>
                </d2>
                <d2 n="EnumTemplates" ckt="Guid" cvt="EnumValueTemplate">
                  <v>6ecff51c-9b8f-4338-aab0-67c2b31b07e9</v>
                  <o>
                    <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                    <l n="Values" t="ArrayList" cet="EnumEntry">
                      <o>
                        <v n="Identifier">"None"</v>
                        <v n="Value">0L</v>
                        <v n="Key">"None"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Variable"</v>
                        <v n="Value">1L</v>
                        <v n="Key">"Variable"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Call"</v>
                        <v n="Value">2L</v>
                        <v n="Key">"Call"</v>
                      </o>
                    </l>
                    <v n="BaseType">"INT"</v>
                  </o>
                  <v>79a4fdd5-c859-4de4-aa8d-c03372c880c2</v>
                  <o>
                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                    <l n="Values" t="ArrayList" cet="EnumEntry">
                      <o>
                        <v n="Identifier">"Unspecified"</v>
                        <v n="Value">0L</v>
                        <v n="Key">"Unspecified"</v>
                      </o>
                      <o>
                        <v n="Identifier">"None"</v>
                        <v n="Value">1L</v>
                        <v n="Key">"None"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Read"</v>
                        <v n="Value">2L</v>
                        <v n="Key">"Read"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Write"</v>
                        <v n="Value">3L</v>
                        <v n="Key">"Write"</v>
                      </o>
                      <o>
                        <v n="Identifier">"ReadWrite"</v>
                        <v n="Value">4L</v>
                        <v n="Key">"ReadWrite"</v>
                      </o>
                    </l>
                    <v n="BaseType">"INT"</v>
                  </o>
                </d2>
                <v n="ImplId">1L</v>
              </o>
            </Data>
            <TypeList>
              <Type n="ArrayList">System.Collections.ArrayList</Type>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="BoolValue">{89e1c7bb-c9f8-4be3-b8a7-019cdbb9f7e8}</Type>
              <Type n="EnumEntry">{4185e6da-1717-44c9-b705-102861764479}</Type>
              <Type n="EnumValue">{4dd7572b-4b9d-4d35-963e-6a34a4aaa5c1}</Type>
              <Type n="EnumValueTemplate">{d6bfe4f0-d62f-4b5f-9f95-2bbeb1950e28}</Type>
              <Type n="Guid">System.Guid</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="SFCActionAssociation">{a94bb75d-5fb3-40ad-9d01-41d5b980784d}</Type>
              <Type n="SFCAttribute">{21f3f16e-04fa-4637-b6b7-d84e4192e99f}</Type>
              <Type n="SFCAttributeCategory">{679adacf-f2a4-4167-a3f7-d21cfc5d451f}</Type>
              <Type n="SFCAttributeDescription">{d851789d-af2c-4990-9d48-a7bdc9181773}</Type>
              <Type n="SFCElementList">{587d6556-cfe6-4e76-9cc9-fc0daf0c8c29}</Type>
              <Type n="SFCImplementationObject">{74f81948-1328-492c-b6c1-a9ea72048b28}</Type>
              <Type n="SFCJump">{7e39ac27-154f-419a-a255-6a6cf37d5ed0}</Type>
              <Type n="SFCSegment">{f1db7f6f-4774-46a6-ad9b-a94414f875fc}</Type>
              <Type n="SFCStep">{86ee92a2-d863-4136-be27-82b36d84211c}</Type>
              <Type n="SFCTransition">{4ecb29e8-a90a-4646-84ac-2ff54215ab29}</Type>
              <Type n="String">System.String</Type>
              <Type n="StringValue">{778c8bac-3fa0-41e1-99d3-2b628d12d3e5}</Type>
            </TypeList>
          </XmlArchive>
        </SFC>
      </Implementation>
      <ObjectProperties>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="SFCProperty">
              <n n="SFCErrorAnalyzation" />
              <n n="SFCErrorAnalyzationTable" />
              <n n="SFCCurrentSteps" />
              <n n="SFCMetaSteps" />
              <v n="Title">"IecSfc"</v>
              <v n="Company">"System"</v>
              <v n="Version">"4.4.0.0"</v>
              <v n="Namespace">""</v>
              <d2 n="Flags" ckt="Flags" cvt="SFCPropertyFlagData">
                <v>EnableLimit</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Init</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Reset</v>
                <o>
                  <v n="Use">true</v>
                  <v n="Declare">true</v>
                </o>
                <v>QuitError</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Pause</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Error</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Trans</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>ErrorStep</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>ErrorPOU</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>CurrentStep</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Tip</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>TipMode</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>SFCErrorAnalyzation</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>SFCErrorAnalyzationTable</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>CurrentSteps</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>MetaSteps</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">false</v>
                </o>
              </d2>
              <v n="CalcActiveTransOnly">true</v>
              <v n="UseDefaults">false</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="Flags">{27d8150b-ef58-4fff-8da1-1f7dd5f9ea51}</Type>
            <Type n="SFCProperty">{58548d2c-f1b1-453d-9195-66c94e2a3ae0}</Type>
            <Type n="SFCPropertyFlagData">{24565a38-6368-4874-ab9a-0ef7ec269521}</Type>
            <Type n="String">System.String</Type>
          </TypeList>
        </XmlArchive>
      </ObjectProperties>
    </Action>
    <Action Name="Deaktivieren" Id="{794dff7e-5fd1-43f4-b7d2-a9e5284cf510}" FolderPath="00_Hilfsaktionen\">
      <Implementation>
        <ST><![CDATA[P2P_Bewegung.bExecute := FALSE;]]></ST>
      </Implementation>
    </Action>
    <Action Name="Skills" Id="{be3da68c-b614-492f-8b70-a1b7e3adc248}">
      <Implementation>
        <CFC>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCImplementationObject">
                <o n="Items" t="CFCItemList">
                  <l2 n="InnerList">
                    <o t="CFCOutputElement">
                      <o n="Input" t="CFCInputPinWithSetReset">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="ProcessValue">""</v>
                        <v n="Access" t="ProcessValueAccess">None</v>
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">54L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"Anlage.UR5.Prozessvariablen"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">55L</v>
                      </o>
                      <v n="PageArea">4</v>
                      <v n="Bounds">"32, 10, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">53L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">61L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"GVL.SystemCommand"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">62L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"9, 5, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">60L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">38L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"Anlage.UR5.P_State"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">39L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"13, 6, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">37L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">41L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"GVL.SystemState"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">42L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"11, 7, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">40L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">44L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"Position"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">45L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"14, 8, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">43L</v>
                    </o>
                    <o t="CFCOutputElement">
                      <o n="Input" t="CFCInputPinWithSetReset">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="ProcessValue">""</v>
                        <v n="Access" t="ProcessValueAccess">None</v>
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">51L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"Anlage.UR5.iSkillCommand_1"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">52L</v>
                      </o>
                      <v n="PageArea">4</v>
                      <v n="Bounds">"32, 4, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">50L</v>
                    </o>
                    <o t="CFCBoxElement">
                      <o n="Inputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCInputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">10L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">58L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">14L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">16L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">18L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Outputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCOutputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">20L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">22L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">24L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">26L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">28L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">30L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">32L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Texts" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCText">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"bExecute"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">11L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"iSysCommand"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">59L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"iObjState"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">15L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"iSysState"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">17L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"sProzessvariablen"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">19L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"iSkillCommand"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">21L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"bDone"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">23L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"bBusy"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">25L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"bLimit"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">27L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"bError"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">29L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"iErrorID"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">31L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"sObjektvariablen"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">33L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"Skill_Position_anfahren"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">8L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"P2P_Bewegung"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">9L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Parameters" t="CFCItemList">
                        <l2 n="InnerList" />
                      </o>
                      <n n="PreparedParameters" />
                      <v n="PageArea">0</v>
                      <v n="Bounds">"20, 2, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="EnEno">false</v>
                      <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="Forced">false</v>
                      <v n="IsFeedbackStart">false</v>
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">1L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">38L</v>
                      <v n="DestPinId">14L</v>
                      <v n="Id">47L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">41L</v>
                      <v n="DestPinId">16L</v>
                      <v n="Id">48L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">44L</v>
                      <v n="DestPinId">18L</v>
                      <v n="Id">49L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">32L</v>
                      <v n="DestPinId">54L</v>
                      <v n="Id">56L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">20L</v>
                      <v n="DestPinId">51L</v>
                      <v n="Id">57L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">61L</v>
                      <v n="DestPinId">58L</v>
                      <v n="Id">64L</v>
                    </o>
                  </l2>
                </o>
                <n n="ParameterInitializationMethodGenerator" />
                <o n="RoutingPathTable" t="CFCRoutingPathTable">
                  <d2 n="InnerDictionary" ckt="CFCRoutingConnection" cvt="CFCPointList">
                    <o>
                      <v n="ConnectionId">57L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">31</v>
                        <v n="Y">4</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">true</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">31</v>
                          <v n="Y">4</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">0</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">56L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">31</v>
                        <v n="Y">10</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">true</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">31</v>
                          <v n="Y">10</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">0</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">49L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">19</v>
                        <v n="Y">8</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">true</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">19</v>
                          <v n="Y">8</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">0</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">48L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">19</v>
                        <v n="Y">7</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">true</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">19</v>
                          <v n="Y">7</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">0</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">47L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">19</v>
                        <v n="Y">6</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">true</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">19</v>
                          <v n="Y">6</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">0</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">64L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">18</v>
                        <v n="Y">5</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">18</v>
                          <v n="Y">5</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">19</v>
                          <v n="Y">5</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                  </d2>
                </o>
                <v n="AutoSizeCanvas">true</v>
                <v n="CanvasWidth">43</v>
                <v n="CanvasHeight">13</v>
                <n n="EditorConfiguration" />
                <v n="AreElementsSpaceOptimized">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCBoxElement">{f5becf35-b1f3-4274-b411-81d4b63a1516}</Type>
              <Type n="CFCConnection">{5ae2e111-ecff-4a21-b647-2d4da63f8db7}</Type>
              <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
              <Type n="CFCInputElement">{d51129f5-df27-4886-99d1-c564d2e2c1f6}</Type>
              <Type n="CFCInputPin">{c994f6e0-311a-4a1c-bc38-75fe34892406}</Type>
              <Type n="CFCInputPinWithSetReset">{5c3476a8-05c5-430e-861c-9cfa51d68ca8}</Type>
              <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
              <Type n="CFCOutputElement">{8d9e2b78-3efe-4fe4-8160-f3a7381ddd8f}</Type>
              <Type n="CFCOutputPin">{65582d84-cf18-4ca0-be59-bf5a3d00b8f8}</Type>
              <Type n="CFCPoint">{b3e42b54-b8f2-45d3-825d-747f82f244a0}</Type>
              <Type n="CFCPointList">{584effbc-813e-443a-bf78-ad9c8d49db41}</Type>
              <Type n="CFCRoutingConnection">{93c117eb-0884-403b-b01e-28b89f47e041}</Type>
              <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
              <Type n="CFCText">{72f2b13f-5349-4a8a-bbe6-2bccf3f42179}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="KindOfCall">{77f43dfe-ca6a-4869-828f-7609d8ed6ea6}</Type>
              <Type n="ProcessValueAccess">{88453c7d-d652-4a27-a1b0-a1953be49a5c}</Type>
              <Type n="SetReset">{24449d48-c96a-49c4-b9d1-a4ea34aedce3}</Type>
              <Type n="SetResetRef">{233bc97c-69fe-4d29-b40e-a9a9b854044e}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </CFC>
      </Implementation>
      <ObjectProperties>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="CFCProperty">
              <v n="UseExplicitExecutionOrder">false</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
          </TypeList>
        </XmlArchive>
      </ObjectProperties>
    </Action>
    <Action Name="Zuweisung_1" Id="{4f3116a9-3ff2-4b0c-8a6f-0b27a684be9a}" FolderPath="01_Zusweisung\">
      <Implementation>
        <ST><![CDATA[Position := Position_1;]]></ST>
      </Implementation>
    </Action>
    <Action Name="Zuweisung_2" Id="{64ea0b0e-bf22-49c7-bc8c-2f73002044aa}" FolderPath="01_Zusweisung\">
      <Implementation>
        <ST><![CDATA[Position := Position_2;]]></ST>
      </Implementation>
    </Action>
    <Action Name="Zuweisung_DOWN" Id="{53219e2a-818a-43c1-8682-428e3cb1d6f2}" FolderPath="01_Zusweisung\">
      <Implementation>
        <ST><![CDATA[Position := Position_DOWN;]]></ST>
      </Implementation>
    </Action>
    <Action Name="Zuweisung_UP" Id="{9b099142-50b6-41b3-977a-da8325f4acd5}" FolderPath="01_Zusweisung\">
      <Implementation>
        <ST><![CDATA[Position := Position_UP;]]></ST>
      </Implementation>
    </Action>
  </POU>
</TcPlcObject>