<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{8cc3ee42-67a9-4667-b58e-96feb4991c55}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR_INPUT
	SysCommand			:SystemCommand;
	SkillCommand		:Skillcommand;
	testProcessValue	:Prozessvariablen; 
	
	Switch				:BOOL;

	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Anlage();
TestAblauf();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>