<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Greifer" Id="{29489103-a9cc-4ccd-8b54-c54ca0ae9cd0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Greifer EXTENDS GrundstrukturObjekt
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>