<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{312d8d08-fddc-42b7-8da4-cd7f10cc1961}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Aufrufen der Objekte
Anlage();
// Aufrufen der Skills
SkillSet();
// Aufrufen der Systenparameterzuweisung 
Systemparameter();
// Aufrunfen des Zustandshandlings
Zustandshandling();
// Temporäre Punktedatenbank
PunkteZuweisung_Temp();

// Aufrufen von Testablauf
AP_1();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>