<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="TestSkill" Id="{38ecaf2b-cc0a-4fd9-a58f-1661e21234c7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TestSkill
VAR_INPUT
	InVar_1			:BOOL;
	InVar_2			:BOOL;
END_VAR
VAR_OUTPUT
	OutVar_1		:BOOL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>