<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="Seq_Ausrichten_MPlate" Id="{aa0a329e-1383-4fc8-a7ba-ba7cada9e1dd}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Seq_Ausrichten_MPlate EXTENDS FB_Basis IMPLEMENTS I_Sequenz
VAR_INPUT
	// Skillzuweisung
	R_Move					:I_Skill_RoboterErweitert;
	G_Move					:I_Skill_SmartGreifer;
	
	// Prozessparameter		
	RobParam				:ARRAY[0..4] OF sRoboterProzessVariablen;
	GripParam				:sSmartGreiferProzessVariablen;
	ErreichtParam			:sKraftVariablen;
END_VAR
VAR_OUTPUT
END_VAR
VAR
	// Interne Sequenzen
	Seq_Ausrichten			:Seq_Ausrichten;	

	// Interne Paramater 
	Ausrichten_Pos			:ARRAY[0..1] OF sRoboterProzessVariablen;
	ErreichtParamReset		:sKraftVariablen;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Ablauf
ACT_Ablauf();

// Zustandshandling
CASE iState OF
	0:	// BEREIT
		IF bStart THEN
			iState := 1;
		END_IF
	1:	// LAUFEND
		IF eSysCommand = 4 THEN
			bReset := TRUE;
			SFCReset := TRUE;
		END_IF
		
		IF bBeendet OR bReset THEN
			bReset := FALSE;
			SFCReset := FALSE;
			iState := 0;
		END_IF
	2: // ABGESCHLOSSEN
		IF SFCCurrentStep = 'Init' THEN
			iState := 0;
		END_IF
END_CASE]]></ST>
    </Implementation>
    <Folder Name="01_Zuweisung" Id="{3c37cb1c-75de-45c0-bae5-d7c1201c9aa4}" />
    <Action Name="ACT_Ablauf" Id="{62e931ce-4889-4fd6-8793-516eb185be1b}">
      <Implementation>
        <SFC>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="SFCImplementationObject">
                <o n="Root" t="SFCSegment">
                  <o n="ElementList" t="SFCElementList">
                    <l2 n="InnerList">
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Init"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">4L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">5L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">6L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">7L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"TRUE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">8L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">9L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">10L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">11L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">12L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">13L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">14L</v>
                            <v n="IdParent">3L</v>
                          </o>
                        </l2>
                        <v n="Id">3L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Init__to__R1_Start_Pos"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"bStart"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">16L</v>
                            <v n="IdParent">15L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">17L</v>
                            <v n="IdParent">15L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">18L</v>
                            <v n="IdParent">15L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">19L</v>
                            <v n="IdParent">15L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">20L</v>
                            <v n="IdParent">15L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">21L</v>
                            <v n="IdParent">15L</v>
                          </o>
                        </l2>
                        <v n="Id">15L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCBranch">
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" cet="SFCSegment">
                            <o>
                              <o n="ElementList" t="SFCElementList">
                                <l2 n="InnerList">
                                  <o t="SFCStep">
                                    <n n="EmbeddedMainAction" />
                                    <n n="EmbeddedEntryAction" />
                                    <n n="EmbeddedExitAction" />
                                    <l2 n="EmbeddedMainActionProperties" />
                                    <l2 n="EmbeddedEntryActionProperties" />
                                    <l2 n="EmbeddedExitActionProperties" />
                                    <o n="ElementList" t="SFCElementList">
                                      <l2 n="InnerList" cet="SFCActionAssociation">
                                        <o>
                                          <l2 n="Attributes" cet="SFCAttribute">
                                            <o>
                                              <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">"R1"</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">438L</v>
                                              <v n="IdParent">437L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">""</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">439L</v>
                                              <v n="IdParent">437L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                              <o n="Value" t="BoolValue">
                                                <v n="Value">"FALSE"</v>
                                                <v n="DefaultValue">"FALSE"</v>
                                              </o>
                                              <v n="Id">440L</v>
                                              <v n="IdParent">437L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                              <o n="Value" t="EnumValue">
                                                <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                                <n n="BaseType" />
                                                <v n="Value">"0"</v>
                                                <v n="DefaultValue">"0"</v>
                                              </o>
                                              <v n="Id">441L</v>
                                              <v n="IdParent">437L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">"N"</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">442L</v>
                                              <v n="IdParent">437L</v>
                                            </o>
                                          </l2>
                                          <v n="Id">437L</v>
                                          <v n="IdParent">26L</v>
                                        </o>
                                        <o>
                                          <l2 n="Attributes" cet="SFCAttribute">
                                            <o>
                                              <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">"R_Move.M_Start"</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">444L</v>
                                              <v n="IdParent">443L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">""</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">445L</v>
                                              <v n="IdParent">443L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                              <o n="Value" t="BoolValue">
                                                <v n="Value">"FALSE"</v>
                                                <v n="DefaultValue">"FALSE"</v>
                                              </o>
                                              <v n="Id">446L</v>
                                              <v n="IdParent">443L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                              <o n="Value" t="EnumValue">
                                                <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                                <n n="BaseType" />
                                                <v n="Value">"0"</v>
                                                <v n="DefaultValue">"0"</v>
                                              </o>
                                              <v n="Id">447L</v>
                                              <v n="IdParent">443L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">"P"</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">448L</v>
                                              <v n="IdParent">443L</v>
                                            </o>
                                          </l2>
                                          <v n="Id">443L</v>
                                          <v n="IdParent">26L</v>
                                        </o>
                                      </l2>
                                    </o>
                                    <l2 n="Attributes" cet="SFCAttribute">
                                      <o>
                                        <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">"R1_Start_Pos"</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">27L</v>
                                        <v n="IdParent">26L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">28L</v>
                                        <v n="IdParent">26L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">29L</v>
                                        <v n="IdParent">26L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                        <o n="Value" t="EnumValue">
                                          <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                          <n n="BaseType" />
                                          <v n="Value">"0"</v>
                                          <v n="DefaultValue">"0"</v>
                                        </o>
                                        <v n="Id">30L</v>
                                        <v n="IdParent">26L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">31L</v>
                                        <v n="IdParent">26L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">32L</v>
                                        <v n="IdParent">26L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">33L</v>
                                        <v n="IdParent">26L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">34L</v>
                                        <v n="IdParent">26L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">35L</v>
                                        <v n="IdParent">26L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">36L</v>
                                        <v n="IdParent">26L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">37L</v>
                                        <v n="IdParent">26L</v>
                                      </o>
                                    </l2>
                                    <v n="Id">26L</v>
                                    <v n="IdParent">107L</v>
                                  </o>
                                  <o t="SFCTransition">
                                    <v n="VariableName">"R1_Start_Pos__to__Wait1_1"</v>
                                    <n n="EmbeddedTransition" />
                                    <l2 n="EmbeddedTransitionProperties" />
                                    <l2 n="Attributes" cet="SFCAttribute">
                                      <o>
                                        <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">"R_Move.P_State = 2"</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">324L</v>
                                        <v n="IdParent">323L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">325L</v>
                                        <v n="IdParent">323L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">326L</v>
                                        <v n="IdParent">323L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                        <o n="Value" t="EnumValue">
                                          <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                          <n n="BaseType" />
                                          <v n="Value">"0"</v>
                                          <v n="DefaultValue">"0"</v>
                                        </o>
                                        <v n="Id">327L</v>
                                        <v n="IdParent">323L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">328L</v>
                                        <v n="IdParent">323L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                        <o n="Value" t="EnumValue">
                                          <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                          <n n="BaseType" />
                                          <v n="Value">"0"</v>
                                          <v n="DefaultValue">"0"</v>
                                        </o>
                                        <v n="Id">329L</v>
                                        <v n="IdParent">323L</v>
                                      </o>
                                    </l2>
                                    <v n="Id">323L</v>
                                    <v n="IdParent">107L</v>
                                  </o>
                                  <o t="SFCStep">
                                    <n n="EmbeddedMainAction" />
                                    <n n="EmbeddedEntryAction" />
                                    <n n="EmbeddedExitAction" />
                                    <l2 n="EmbeddedMainActionProperties" />
                                    <l2 n="EmbeddedEntryActionProperties" />
                                    <l2 n="EmbeddedExitActionProperties" />
                                    <o n="ElementList" t="SFCElementList">
                                      <l2 n="InnerList" />
                                    </o>
                                    <l2 n="Attributes" cet="SFCAttribute">
                                      <o>
                                        <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">"Wait1_1"</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">331L</v>
                                        <v n="IdParent">330L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">332L</v>
                                        <v n="IdParent">330L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">333L</v>
                                        <v n="IdParent">330L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                        <o n="Value" t="EnumValue">
                                          <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                          <n n="BaseType" />
                                          <v n="Value">"0"</v>
                                          <v n="DefaultValue">"0"</v>
                                        </o>
                                        <v n="Id">334L</v>
                                        <v n="IdParent">330L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">335L</v>
                                        <v n="IdParent">330L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">336L</v>
                                        <v n="IdParent">330L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">337L</v>
                                        <v n="IdParent">330L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">338L</v>
                                        <v n="IdParent">330L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">339L</v>
                                        <v n="IdParent">330L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">340L</v>
                                        <v n="IdParent">330L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">341L</v>
                                        <v n="IdParent">330L</v>
                                      </o>
                                    </l2>
                                    <v n="Id">330L</v>
                                    <v n="IdParent">107L</v>
                                  </o>
                                </l2>
                              </o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">108L</v>
                                  <v n="IdParent">107L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">109L</v>
                                  <v n="IdParent">107L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">110L</v>
                                  <v n="IdParent">107L</v>
                                </o>
                              </l2>
                              <v n="Id">107L</v>
                              <v n="IdParent">102L</v>
                            </o>
                            <o>
                              <o n="ElementList" t="SFCElementList">
                                <l2 n="InnerList">
                                  <o t="SFCStep">
                                    <n n="EmbeddedMainAction" />
                                    <n n="EmbeddedEntryAction" />
                                    <n n="EmbeddedExitAction" />
                                    <l2 n="EmbeddedMainActionProperties" />
                                    <l2 n="EmbeddedEntryActionProperties" />
                                    <l2 n="EmbeddedExitActionProperties" />
                                    <o n="ElementList" t="SFCElementList">
                                      <l2 n="InnerList" cet="SFCActionAssociation">
                                        <o>
                                          <l2 n="Attributes" cet="SFCAttribute">
                                            <o>
                                              <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">"G1"</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">498L</v>
                                              <v n="IdParent">497L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">""</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">499L</v>
                                              <v n="IdParent">497L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                              <o n="Value" t="BoolValue">
                                                <v n="Value">"FALSE"</v>
                                                <v n="DefaultValue">"FALSE"</v>
                                              </o>
                                              <v n="Id">500L</v>
                                              <v n="IdParent">497L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                              <o n="Value" t="EnumValue">
                                                <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                                <n n="BaseType" />
                                                <v n="Value">"0"</v>
                                                <v n="DefaultValue">"0"</v>
                                              </o>
                                              <v n="Id">501L</v>
                                              <v n="IdParent">497L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">"N"</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">502L</v>
                                              <v n="IdParent">497L</v>
                                            </o>
                                          </l2>
                                          <v n="Id">497L</v>
                                          <v n="IdParent">115L</v>
                                        </o>
                                        <o>
                                          <l2 n="Attributes" cet="SFCAttribute">
                                            <o>
                                              <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">"G_Move.M_Start"</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">504L</v>
                                              <v n="IdParent">503L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">""</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">505L</v>
                                              <v n="IdParent">503L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                              <o n="Value" t="BoolValue">
                                                <v n="Value">"FALSE"</v>
                                                <v n="DefaultValue">"FALSE"</v>
                                              </o>
                                              <v n="Id">506L</v>
                                              <v n="IdParent">503L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                              <o n="Value" t="EnumValue">
                                                <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                                <n n="BaseType" />
                                                <v n="Value">"0"</v>
                                                <v n="DefaultValue">"0"</v>
                                              </o>
                                              <v n="Id">507L</v>
                                              <v n="IdParent">503L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">"P"</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">508L</v>
                                              <v n="IdParent">503L</v>
                                            </o>
                                          </l2>
                                          <v n="Id">503L</v>
                                          <v n="IdParent">115L</v>
                                        </o>
                                      </l2>
                                    </o>
                                    <l2 n="Attributes" cet="SFCAttribute">
                                      <o>
                                        <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">"G1_Zu"</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">116L</v>
                                        <v n="IdParent">115L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">117L</v>
                                        <v n="IdParent">115L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">118L</v>
                                        <v n="IdParent">115L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                        <o n="Value" t="EnumValue">
                                          <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                          <n n="BaseType" />
                                          <v n="Value">"0"</v>
                                          <v n="DefaultValue">"0"</v>
                                        </o>
                                        <v n="Id">119L</v>
                                        <v n="IdParent">115L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">120L</v>
                                        <v n="IdParent">115L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">121L</v>
                                        <v n="IdParent">115L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">122L</v>
                                        <v n="IdParent">115L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">123L</v>
                                        <v n="IdParent">115L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">124L</v>
                                        <v n="IdParent">115L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">125L</v>
                                        <v n="IdParent">115L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">126L</v>
                                        <v n="IdParent">115L</v>
                                      </o>
                                    </l2>
                                    <v n="Id">115L</v>
                                    <v n="IdParent">111L</v>
                                  </o>
                                  <o t="SFCTransition">
                                    <v n="VariableName">"G1_Zu__to__Wait1_2"</v>
                                    <n n="EmbeddedTransition" />
                                    <l2 n="EmbeddedTransitionProperties" />
                                    <l2 n="Attributes" cet="SFCAttribute">
                                      <o>
                                        <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">"G_Move.P_State = 2"</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">343L</v>
                                        <v n="IdParent">342L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">344L</v>
                                        <v n="IdParent">342L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">345L</v>
                                        <v n="IdParent">342L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                        <o n="Value" t="EnumValue">
                                          <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                          <n n="BaseType" />
                                          <v n="Value">"0"</v>
                                          <v n="DefaultValue">"0"</v>
                                        </o>
                                        <v n="Id">346L</v>
                                        <v n="IdParent">342L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">347L</v>
                                        <v n="IdParent">342L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                        <o n="Value" t="EnumValue">
                                          <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                          <n n="BaseType" />
                                          <v n="Value">"0"</v>
                                          <v n="DefaultValue">"0"</v>
                                        </o>
                                        <v n="Id">348L</v>
                                        <v n="IdParent">342L</v>
                                      </o>
                                    </l2>
                                    <v n="Id">342L</v>
                                    <v n="IdParent">111L</v>
                                  </o>
                                  <o t="SFCStep">
                                    <n n="EmbeddedMainAction" />
                                    <n n="EmbeddedEntryAction" />
                                    <n n="EmbeddedExitAction" />
                                    <l2 n="EmbeddedMainActionProperties" />
                                    <l2 n="EmbeddedEntryActionProperties" />
                                    <l2 n="EmbeddedExitActionProperties" />
                                    <o n="ElementList" t="SFCElementList">
                                      <l2 n="InnerList" />
                                    </o>
                                    <l2 n="Attributes" cet="SFCAttribute">
                                      <o>
                                        <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">"Wait1_2"</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">350L</v>
                                        <v n="IdParent">349L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">351L</v>
                                        <v n="IdParent">349L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">352L</v>
                                        <v n="IdParent">349L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                        <o n="Value" t="EnumValue">
                                          <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                          <n n="BaseType" />
                                          <v n="Value">"0"</v>
                                          <v n="DefaultValue">"0"</v>
                                        </o>
                                        <v n="Id">353L</v>
                                        <v n="IdParent">349L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">354L</v>
                                        <v n="IdParent">349L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">355L</v>
                                        <v n="IdParent">349L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">356L</v>
                                        <v n="IdParent">349L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">357L</v>
                                        <v n="IdParent">349L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">358L</v>
                                        <v n="IdParent">349L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">359L</v>
                                        <v n="IdParent">349L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">360L</v>
                                        <v n="IdParent">349L</v>
                                      </o>
                                    </l2>
                                    <v n="Id">349L</v>
                                    <v n="IdParent">111L</v>
                                  </o>
                                </l2>
                              </o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">112L</v>
                                  <v n="IdParent">111L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">113L</v>
                                  <v n="IdParent">111L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">114L</v>
                                  <v n="IdParent">111L</v>
                                </o>
                              </l2>
                              <v n="Id">111L</v>
                              <v n="IdParent">102L</v>
                            </o>
                          </l2>
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">103L</v>
                            <v n="IdParent">102L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">104L</v>
                            <v n="IdParent">102L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">105L</v>
                            <v n="IdParent">102L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"TRUE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">106L</v>
                            <v n="IdParent">102L</v>
                          </o>
                        </l2>
                        <v n="Id">102L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Wait1_1__to__R2_nOffset_Z"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"R_Move.P_State = 0 AND G_Move.P_State = 0"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">96L</v>
                            <v n="IdParent">95L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">97L</v>
                            <v n="IdParent">95L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">98L</v>
                            <v n="IdParent">95L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">99L</v>
                            <v n="IdParent">95L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">100L</v>
                            <v n="IdParent">95L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">101L</v>
                            <v n="IdParent">95L</v>
                          </o>
                        </l2>
                        <v n="Id">95L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" cet="SFCActionAssociation">
                            <o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"R2"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">462L</v>
                                  <v n="IdParent">461L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">463L</v>
                                  <v n="IdParent">461L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">464L</v>
                                  <v n="IdParent">461L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">465L</v>
                                  <v n="IdParent">461L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"N"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">466L</v>
                                  <v n="IdParent">461L</v>
                                </o>
                              </l2>
                              <v n="Id">461L</v>
                              <v n="IdParent">241L</v>
                            </o>
                            <o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"R_Move.M_Start"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">468L</v>
                                  <v n="IdParent">467L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">469L</v>
                                  <v n="IdParent">467L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">470L</v>
                                  <v n="IdParent">467L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">471L</v>
                                  <v n="IdParent">467L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"P"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">472L</v>
                                  <v n="IdParent">467L</v>
                                </o>
                              </l2>
                              <v n="Id">467L</v>
                              <v n="IdParent">241L</v>
                            </o>
                          </l2>
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"R2_nOffset_Z"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">242L</v>
                            <v n="IdParent">241L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">243L</v>
                            <v n="IdParent">241L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">244L</v>
                            <v n="IdParent">241L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">245L</v>
                            <v n="IdParent">241L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">246L</v>
                            <v n="IdParent">241L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">247L</v>
                            <v n="IdParent">241L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">248L</v>
                            <v n="IdParent">241L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">249L</v>
                            <v n="IdParent">241L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">250L</v>
                            <v n="IdParent">241L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">251L</v>
                            <v n="IdParent">241L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">252L</v>
                            <v n="IdParent">241L</v>
                          </o>
                        </l2>
                        <v n="Id">241L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"R2_nOffset_Z__to__Wait_2"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"R_Move.P_State = 2"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">362L</v>
                            <v n="IdParent">361L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">363L</v>
                            <v n="IdParent">361L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">364L</v>
                            <v n="IdParent">361L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">365L</v>
                            <v n="IdParent">361L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">366L</v>
                            <v n="IdParent">361L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">367L</v>
                            <v n="IdParent">361L</v>
                          </o>
                        </l2>
                        <v n="Id">361L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Wait_2"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">369L</v>
                            <v n="IdParent">368L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">370L</v>
                            <v n="IdParent">368L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">371L</v>
                            <v n="IdParent">368L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">372L</v>
                            <v n="IdParent">368L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">373L</v>
                            <v n="IdParent">368L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">374L</v>
                            <v n="IdParent">368L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">375L</v>
                            <v n="IdParent">368L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">376L</v>
                            <v n="IdParent">368L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">377L</v>
                            <v n="IdParent">368L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">378L</v>
                            <v n="IdParent">368L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">379L</v>
                            <v n="IdParent">368L</v>
                          </o>
                        </l2>
                        <v n="Id">368L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Wait_2__to__S1_Ausrichten"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"R_Move.P_State = 0"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">261L</v>
                            <v n="IdParent">260L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">262L</v>
                            <v n="IdParent">260L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">263L</v>
                            <v n="IdParent">260L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">264L</v>
                            <v n="IdParent">260L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">265L</v>
                            <v n="IdParent">260L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">266L</v>
                            <v n="IdParent">260L</v>
                          </o>
                        </l2>
                        <v n="Id">260L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" cet="SFCActionAssociation">
                            <o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"S1"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">486L</v>
                                  <v n="IdParent">485L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">487L</v>
                                  <v n="IdParent">485L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">488L</v>
                                  <v n="IdParent">485L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">489L</v>
                                  <v n="IdParent">485L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"N"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">490L</v>
                                  <v n="IdParent">485L</v>
                                </o>
                              </l2>
                              <v n="Id">485L</v>
                              <v n="IdParent">267L</v>
                            </o>
                            <o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"Seq_Ausrichten.M_Start"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">492L</v>
                                  <v n="IdParent">491L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">493L</v>
                                  <v n="IdParent">491L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">494L</v>
                                  <v n="IdParent">491L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">495L</v>
                                  <v n="IdParent">491L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"P"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">496L</v>
                                  <v n="IdParent">491L</v>
                                </o>
                              </l2>
                              <v n="Id">491L</v>
                              <v n="IdParent">267L</v>
                            </o>
                          </l2>
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"S1_Ausrichten"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">268L</v>
                            <v n="IdParent">267L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">269L</v>
                            <v n="IdParent">267L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">270L</v>
                            <v n="IdParent">267L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">271L</v>
                            <v n="IdParent">267L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">272L</v>
                            <v n="IdParent">267L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">273L</v>
                            <v n="IdParent">267L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">274L</v>
                            <v n="IdParent">267L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">275L</v>
                            <v n="IdParent">267L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">276L</v>
                            <v n="IdParent">267L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">277L</v>
                            <v n="IdParent">267L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">278L</v>
                            <v n="IdParent">267L</v>
                          </o>
                        </l2>
                        <v n="Id">267L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"S1_Ausrichten__to__R3_Offset_Z"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Seq_Ausrichten.P_Finished"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">381L</v>
                            <v n="IdParent">380L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">382L</v>
                            <v n="IdParent">380L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">383L</v>
                            <v n="IdParent">380L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">384L</v>
                            <v n="IdParent">380L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">385L</v>
                            <v n="IdParent">380L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">386L</v>
                            <v n="IdParent">380L</v>
                          </o>
                        </l2>
                        <v n="Id">380L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" cet="SFCActionAssociation">
                            <o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"R3"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">474L</v>
                                  <v n="IdParent">473L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">475L</v>
                                  <v n="IdParent">473L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">476L</v>
                                  <v n="IdParent">473L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">477L</v>
                                  <v n="IdParent">473L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"N"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">478L</v>
                                  <v n="IdParent">473L</v>
                                </o>
                              </l2>
                              <v n="Id">473L</v>
                              <v n="IdParent">286L</v>
                            </o>
                            <o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"R_Move.M_Start"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">480L</v>
                                  <v n="IdParent">479L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">481L</v>
                                  <v n="IdParent">479L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">482L</v>
                                  <v n="IdParent">479L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">483L</v>
                                  <v n="IdParent">479L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"P"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">484L</v>
                                  <v n="IdParent">479L</v>
                                </o>
                              </l2>
                              <v n="Id">479L</v>
                              <v n="IdParent">286L</v>
                            </o>
                          </l2>
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"R3_Offset_Z"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">287L</v>
                            <v n="IdParent">286L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">288L</v>
                            <v n="IdParent">286L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">289L</v>
                            <v n="IdParent">286L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">290L</v>
                            <v n="IdParent">286L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">291L</v>
                            <v n="IdParent">286L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">292L</v>
                            <v n="IdParent">286L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">293L</v>
                            <v n="IdParent">286L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">294L</v>
                            <v n="IdParent">286L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">295L</v>
                            <v n="IdParent">286L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">296L</v>
                            <v n="IdParent">286L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">297L</v>
                            <v n="IdParent">286L</v>
                          </o>
                        </l2>
                        <v n="Id">286L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"R3_Offset_Z__to__Wait_4"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"R_Move.P_State = 2"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">400L</v>
                            <v n="IdParent">399L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">401L</v>
                            <v n="IdParent">399L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">402L</v>
                            <v n="IdParent">399L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">403L</v>
                            <v n="IdParent">399L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">404L</v>
                            <v n="IdParent">399L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">405L</v>
                            <v n="IdParent">399L</v>
                          </o>
                        </l2>
                        <v n="Id">399L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Wait_4"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">407L</v>
                            <v n="IdParent">406L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">408L</v>
                            <v n="IdParent">406L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">409L</v>
                            <v n="IdParent">406L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">410L</v>
                            <v n="IdParent">406L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">411L</v>
                            <v n="IdParent">406L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">412L</v>
                            <v n="IdParent">406L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">413L</v>
                            <v n="IdParent">406L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">414L</v>
                            <v n="IdParent">406L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">415L</v>
                            <v n="IdParent">406L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">416L</v>
                            <v n="IdParent">406L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">417L</v>
                            <v n="IdParent">406L</v>
                          </o>
                        </l2>
                        <v n="Id">406L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Wait_4__to__Finished"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"R_Move.P_State = 0"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">254L</v>
                            <v n="IdParent">253L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">255L</v>
                            <v n="IdParent">253L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">256L</v>
                            <v n="IdParent">253L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">257L</v>
                            <v n="IdParent">253L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">258L</v>
                            <v n="IdParent">253L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">259L</v>
                            <v n="IdParent">253L</v>
                          </o>
                        </l2>
                        <v n="Id">253L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" cet="SFCActionAssociation">
                            <o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"M_Stop"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">318L</v>
                                  <v n="IdParent">317L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">319L</v>
                                  <v n="IdParent">317L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">320L</v>
                                  <v n="IdParent">317L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">321L</v>
                                  <v n="IdParent">317L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"P"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">322L</v>
                                  <v n="IdParent">317L</v>
                                </o>
                              </l2>
                              <v n="Id">317L</v>
                              <v n="IdParent">298L</v>
                            </o>
                          </l2>
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Finished"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">299L</v>
                            <v n="IdParent">298L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">300L</v>
                            <v n="IdParent">298L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">301L</v>
                            <v n="IdParent">298L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">302L</v>
                            <v n="IdParent">298L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">303L</v>
                            <v n="IdParent">298L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">304L</v>
                            <v n="IdParent">298L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">305L</v>
                            <v n="IdParent">298L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">306L</v>
                            <v n="IdParent">298L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">307L</v>
                            <v n="IdParent">298L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">308L</v>
                            <v n="IdParent">298L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">309L</v>
                            <v n="IdParent">298L</v>
                          </o>
                        </l2>
                        <v n="Id">298L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Finished__to__Init"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"bBeendet"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">311L</v>
                            <v n="IdParent">310L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">312L</v>
                            <v n="IdParent">310L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">313L</v>
                            <v n="IdParent">310L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">314L</v>
                            <v n="IdParent">310L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">315L</v>
                            <v n="IdParent">310L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">316L</v>
                            <v n="IdParent">310L</v>
                          </o>
                        </l2>
                        <v n="Id">310L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCJump">
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Init"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">23L</v>
                            <v n="IdParent">22L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">24L</v>
                            <v n="IdParent">22L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">25L</v>
                            <v n="IdParent">22L</v>
                          </o>
                        </l2>
                        <v n="Id">22L</v>
                        <v n="IdParent">2L</v>
                      </o>
                    </l2>
                  </o>
                  <l2 n="Attributes" cet="SFCAttribute">
                    <o>
                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                      <o n="Value" t="StringValue">
                        <v n="Value">""</v>
                        <v n="DefaultValue">""</v>
                      </o>
                      <v n="Id">509L</v>
                      <v n="IdParent">2L</v>
                    </o>
                    <o>
                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                      <o n="Value" t="StringValue">
                        <v n="Value">""</v>
                        <v n="DefaultValue">""</v>
                      </o>
                      <v n="Id">510L</v>
                      <v n="IdParent">2L</v>
                    </o>
                    <o>
                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                      <o n="Value" t="BoolValue">
                        <v n="Value">"FALSE"</v>
                        <v n="DefaultValue">"FALSE"</v>
                      </o>
                      <v n="Id">511L</v>
                      <v n="IdParent">2L</v>
                    </o>
                  </l2>
                  <v n="Id">2L</v>
                  <v n="IdParent">-1L</v>
                </o>
                <d2 n="Categories" ckt="Guid" cvt="SFCAttributeCategory">
                  <v>1c5c6e05-2bb7-4258-bcee-fd16a540c63c</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Identifier">"Specific"</v>
                    <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                    <v n="Description">"Element type specific properties"</v>
                  </o>
                  <v>20f0fc67-978d-438b-979f-eef294f34ee4</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Identifier">"Actions"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Action definitions"</v>
                  </o>
                  <v>6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Identifier">"Common"</v>
                    <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                    <v n="Description">"Common properties"</v>
                  </o>
                  <v>d336ba06-8a67-4e6b-9697-50f83ba6bdde</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                    <v n="Identifier">"Times"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Time definitions"</v>
                  </o>
                </d2>
                <d2 n="Attributes" ckt="Guid" cvt="SFCAttributeDescription">
                  <v>01580b27-6378-448b-8ecb-0e4b795b58d6</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">true</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                    <v n="Identifier">"Exclude"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Exclude this element from build"</v>
                  </o>
                  <v>23bdaa98-72ec-41f7-817b-9dede5697086</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                    <v n="Identifier">"Parallel"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Sets the branch to parallel mode"</v>
                  </o>
                  <v>38391c6d-6d4a-42f8-8ee7-9f45e5adafa8</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                    <v n="Identifier">"Name"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Name of the element"</v>
                  </o>
                  <v>62e1754b-7629-4e63-9cec-10ae0c536f1f</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                    <v n="Identifier">"Duplication"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Copies the implementation of step actions or transitions with the element. Otherwise, copies the reference to an existing implementation."</v>
                  </o>
                  <v>6844a48e-46c2-4cc8-a185-a478f3b99cc0</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                    <v n="Identifier">"InitStep"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Sets the step as the initial step"</v>
                  </o>
                  <v>700a583f-b4d4-43e4-8c14-629c7cd3bec8</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                    <v n="Identifier">"MainAction"</v>
                    <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Description">"Name of the action to be called if the step is active"</v>
                  </o>
                  <v>7d894980-aeea-405c-a0f6-e2b26429c58f</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">true</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                    <v n="Identifier">"Comment"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Comment of the element"</v>
                  </o>
                  <v>8294df19-5962-4dee-a874-1051dabb0e3e</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                    <v n="Identifier">"Monitoring"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Indicates transition monitoring setting."</v>
                  </o>
                  <v>a2621e18-7de3-4ea6-ae6d-89e9e0b7befd</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                    <v n="Identifier">"ExitAction"</v>
                    <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Description">"Name of the action to be called if the step is deactivated"</v>
                  </o>
                  <v>a6b08bd8-b696-47e3-9cbf-7408b61c9ff8</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                    <v n="Identifier">"EntryAction"</v>
                    <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Description">"Name of the action to be called if the step is activated"</v>
                  </o>
                  <v>b693554c-1b01-4a8d-afde-9e3a46f7465d</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                    <v n="Identifier">"MaxTime"</v>
                    <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                    <v n="Description">"Defines the maximal active time for the step"</v>
                  </o>
                  <v>bc882c11-1e91-4dd8-a6b8-2075724ed18b</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                    <v n="Identifier">"Symbol"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Symbol configuration setting of the element"</v>
                  </o>
                  <v>cacf1a68-236e-47c2-b7b1-1cf9199718cb</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                    <v n="Identifier">"MinTime"</v>
                    <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                    <v n="Description">"Defines the minimal active time for the step"</v>
                  </o>
                  <v>e174fc0d-80b0-4a9e-a530-ca239c249a50</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                    <v n="Identifier">"Qualifier"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Qualifier of the action association"</v>
                  </o>
                </d2>
                <d2 n="EnumTemplates" ckt="Guid" cvt="EnumValueTemplate">
                  <v>6ecff51c-9b8f-4338-aab0-67c2b31b07e9</v>
                  <o>
                    <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                    <l n="Values" t="ArrayList" cet="EnumEntry">
                      <o>
                        <v n="Identifier">"None"</v>
                        <v n="Value">0L</v>
                        <v n="Key">"None"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Variable"</v>
                        <v n="Value">1L</v>
                        <v n="Key">"Variable"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Call"</v>
                        <v n="Value">2L</v>
                        <v n="Key">"Call"</v>
                      </o>
                    </l>
                    <v n="BaseType">"INT"</v>
                  </o>
                  <v>79a4fdd5-c859-4de4-aa8d-c03372c880c2</v>
                  <o>
                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                    <l n="Values" t="ArrayList" cet="EnumEntry">
                      <o>
                        <v n="Identifier">"Unspecified"</v>
                        <v n="Value">0L</v>
                        <v n="Key">"Unspecified"</v>
                      </o>
                      <o>
                        <v n="Identifier">"None"</v>
                        <v n="Value">1L</v>
                        <v n="Key">"None"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Read"</v>
                        <v n="Value">2L</v>
                        <v n="Key">"Read"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Write"</v>
                        <v n="Value">3L</v>
                        <v n="Key">"Write"</v>
                      </o>
                      <o>
                        <v n="Identifier">"ReadWrite"</v>
                        <v n="Value">4L</v>
                        <v n="Key">"ReadWrite"</v>
                      </o>
                    </l>
                    <v n="BaseType">"INT"</v>
                  </o>
                </d2>
                <v n="ImplId">1L</v>
              </o>
            </Data>
            <TypeList>
              <Type n="ArrayList">System.Collections.ArrayList</Type>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="BoolValue">{89e1c7bb-c9f8-4be3-b8a7-019cdbb9f7e8}</Type>
              <Type n="EnumEntry">{4185e6da-1717-44c9-b705-102861764479}</Type>
              <Type n="EnumValue">{4dd7572b-4b9d-4d35-963e-6a34a4aaa5c1}</Type>
              <Type n="EnumValueTemplate">{d6bfe4f0-d62f-4b5f-9f95-2bbeb1950e28}</Type>
              <Type n="Guid">System.Guid</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="SFCActionAssociation">{a94bb75d-5fb3-40ad-9d01-41d5b980784d}</Type>
              <Type n="SFCAttribute">{21f3f16e-04fa-4637-b6b7-d84e4192e99f}</Type>
              <Type n="SFCAttributeCategory">{679adacf-f2a4-4167-a3f7-d21cfc5d451f}</Type>
              <Type n="SFCAttributeDescription">{d851789d-af2c-4990-9d48-a7bdc9181773}</Type>
              <Type n="SFCBranch">{e221b778-bb8f-44ba-8a6a-f796287d4e62}</Type>
              <Type n="SFCElementList">{587d6556-cfe6-4e76-9cc9-fc0daf0c8c29}</Type>
              <Type n="SFCImplementationObject">{74f81948-1328-492c-b6c1-a9ea72048b28}</Type>
              <Type n="SFCJump">{7e39ac27-154f-419a-a255-6a6cf37d5ed0}</Type>
              <Type n="SFCSegment">{f1db7f6f-4774-46a6-ad9b-a94414f875fc}</Type>
              <Type n="SFCStep">{86ee92a2-d863-4136-be27-82b36d84211c}</Type>
              <Type n="SFCTransition">{4ecb29e8-a90a-4646-84ac-2ff54215ab29}</Type>
              <Type n="String">System.String</Type>
              <Type n="StringValue">{778c8bac-3fa0-41e1-99d3-2b628d12d3e5}</Type>
            </TypeList>
          </XmlArchive>
        </SFC>
      </Implementation>
      <ObjectProperties>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="SFCProperty">
              <n n="SFCErrorAnalyzation" />
              <n n="SFCErrorAnalyzationTable" />
              <n n="SFCCurrentSteps" />
              <n n="SFCMetaSteps" />
              <v n="Title">"IecSfc"</v>
              <v n="Company">"System"</v>
              <v n="Version">"4.4.0.0"</v>
              <v n="Namespace">""</v>
              <d2 n="Flags" ckt="Flags" cvt="SFCPropertyFlagData">
                <v>EnableLimit</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Init</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Reset</v>
                <o>
                  <v n="Use">true</v>
                  <v n="Declare">true</v>
                </o>
                <v>QuitError</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Pause</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Error</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Trans</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>ErrorStep</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>ErrorPOU</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>CurrentStep</v>
                <o>
                  <v n="Use">true</v>
                  <v n="Declare">true</v>
                </o>
                <v>Tip</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>TipMode</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>SFCErrorAnalyzation</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>SFCErrorAnalyzationTable</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>CurrentSteps</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>MetaSteps</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">false</v>
                </o>
              </d2>
              <v n="CalcActiveTransOnly">true</v>
              <v n="UseDefaults">false</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="Flags">{27d8150b-ef58-4fff-8da1-1f7dd5f9ea51}</Type>
            <Type n="SFCProperty">{58548d2c-f1b1-453d-9195-66c94e2a3ae0}</Type>
            <Type n="SFCPropertyFlagData">{24565a38-6368-4874-ab9a-0ef7ec269521}</Type>
            <Type n="String">System.String</Type>
          </TypeList>
        </XmlArchive>
      </ObjectProperties>
    </Action>
    <Action Name="G1" Id="{796ee13a-6770-4428-8a91-187977221775}" FolderPath="01_Zuweisung\">
      <Implementation>
        <ST><![CDATA[G_Move.P_SGripperParam := GripParam;]]></ST>
      </Implementation>
    </Action>
    <Action Name="R1" Id="{9e703a3f-5d85-48ff-b0b4-c083ef3c9a33}" FolderPath="01_Zuweisung\">
      <Implementation>
        <ST><![CDATA[R_Move.P_RobotParam := RobParam[0];]]></ST>
      </Implementation>
    </Action>
    <Action Name="R2" Id="{58019613-0f7b-4638-a369-f9ee31c45971}" FolderPath="01_Zuweisung\">
      <Implementation>
        <ST><![CDATA[R_Move.P_RobotParam := RobParam[1];]]></ST>
      </Implementation>
    </Action>
    <Action Name="R3" Id="{025121c3-2dfb-449f-9048-c06e78b51f2f}" FolderPath="01_Zuweisung\">
      <Implementation>
        <ST><![CDATA[R_Move.P_RobotParam := RobParam[4];]]></ST>
      </Implementation>
    </Action>
    <Action Name="S1" Id="{0b362b00-eb52-4c68-b5b2-594863508356}" FolderPath="01_Zuweisung\">
      <Implementation>
        <ST><![CDATA[Ausrichten_Pos[0] := RobParam[2];
Ausrichten_Pos[1] := RobParam[3];

Seq_Ausrichten(	eSysCommand := GVL.SystemCommand,
				R_Move := SkillSet.Move_2P2_Advanced,
				RobParam := Ausrichten_Pos,
				ErreichtParam := ErreichtParam);
			]]></ST>
      </Implementation>
    </Action>
  </POU>
</TcPlcObject>