<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="Seq_Teile_Hohlen" Id="{3ab1661f-bca8-48a2-ae3c-ae654f4f2e0c}" SpecialFunc="None">
    <Declaration><![CDATA[
FUNCTION_BLOCK Seq_Teile_Hohlen EXTENDS FB_Basis
VAR_INPUT
	// Prozessparameter		
	Param_StartPos				:sRoboterProzessVariablen;
	Param_Backenbreite			:USINT;
	
	// Objekt-Schnittstellen
	I_Roboter					:I_Objekt_Roboter;
	I_Greifer					:I_Objekt_SmartGreifer;	
END_VAR
VAR_OUTPUT
END_VAR
VAR
	// Skill-Instanziierung
	Skill_R_P2P				:Skill_Position_anfahren;
	Skill_G_P2P				:Skill_Greifer_Pos_Anfahren;
	
	// Interne Prozessvariablen
	LRobotVar				:sRoboterProzessVariablen;
	LGreiferVar				:sSmartGreiferProzessVariablen;
	LOffsetVar				:LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
// Ablauf
ACT_Ablauf();

// Zustandshandling
CASE iState OF
	0:	// BEREIT
		IF bStart THEN
			iState := 1;
		END_IF
	1:	// LAUFEND
		IF eSysCommand = 4 THEN
			bReset := TRUE;
			SFCReset := TRUE;
		END_IF
		
		IF bBeendet OR bReset THEN
			bReset := FALSE;
			SFCReset := FALSE;
			iState := 0;
		END_IF
	2: // ABGESCHLOSSEN
		IF SFCCurrentStep = 'Init' THEN
			iState := 0;
		END_IF
END_CASE]]></ST>
    </Implementation>
    <Folder Name="00_Resetten" Id="{423a6df8-95e5-4bf4-9beb-6956cb2ad30b}" />
    <Folder Name="01_Zuweisung" Id="{1ec76369-d69f-4367-a471-342380850034}" />
    <Action Name="ACT_Ablauf" Id="{f6f92059-91e4-4a97-9405-188641de22cc}">
      <Implementation>
        <SFC>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="SFCImplementationObject">
                <o n="Root" t="SFCSegment">
                  <o n="ElementList" t="SFCElementList">
                    <l2 n="InnerList">
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Init"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">4L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">5L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">6L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">7L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"TRUE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">8L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">9L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">10L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">11L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">12L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">13L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">14L</v>
                            <v n="IdParent">3L</v>
                          </o>
                        </l2>
                        <v n="Id">3L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Init__to__Start_Pos"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"bStart"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">472L</v>
                            <v n="IdParent">471L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">473L</v>
                            <v n="IdParent">471L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">474L</v>
                            <v n="IdParent">471L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">475L</v>
                            <v n="IdParent">471L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">476L</v>
                            <v n="IdParent">471L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">477L</v>
                            <v n="IdParent">471L</v>
                          </o>
                        </l2>
                        <v n="Id">471L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCBranch">
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" cet="SFCSegment">
                            <o>
                              <o n="ElementList" t="SFCElementList">
                                <l2 n="InnerList" cet="SFCStep">
                                  <o>
                                    <n n="EmbeddedMainAction" />
                                    <n n="EmbeddedEntryAction" />
                                    <n n="EmbeddedExitAction" />
                                    <l2 n="EmbeddedMainActionProperties" />
                                    <l2 n="EmbeddedEntryActionProperties" />
                                    <l2 n="EmbeddedExitActionProperties" />
                                    <o n="ElementList" t="SFCElementList">
                                      <l2 n="InnerList" cet="SFCActionAssociation">
                                        <o>
                                          <l2 n="Attributes" cet="SFCAttribute">
                                            <o>
                                              <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">"Z_Start_Pos"</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">198L</v>
                                              <v n="IdParent">197L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">""</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">199L</v>
                                              <v n="IdParent">197L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                              <o n="Value" t="BoolValue">
                                                <v n="Value">"FALSE"</v>
                                                <v n="DefaultValue">"FALSE"</v>
                                              </o>
                                              <v n="Id">200L</v>
                                              <v n="IdParent">197L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                              <o n="Value" t="EnumValue">
                                                <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                                <n n="BaseType" />
                                                <v n="Value">"0"</v>
                                                <v n="DefaultValue">"0"</v>
                                              </o>
                                              <v n="Id">201L</v>
                                              <v n="IdParent">197L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">"N"</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">202L</v>
                                              <v n="IdParent">197L</v>
                                            </o>
                                          </l2>
                                          <v n="Id">197L</v>
                                          <v n="IdParent">26L</v>
                                        </o>
                                        <o>
                                          <l2 n="Attributes" cet="SFCAttribute">
                                            <o>
                                              <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">"Skill_R_P2P.M_Start"</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">204L</v>
                                              <v n="IdParent">203L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">""</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">205L</v>
                                              <v n="IdParent">203L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                              <o n="Value" t="BoolValue">
                                                <v n="Value">"FALSE"</v>
                                                <v n="DefaultValue">"FALSE"</v>
                                              </o>
                                              <v n="Id">206L</v>
                                              <v n="IdParent">203L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                              <o n="Value" t="EnumValue">
                                                <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                                <n n="BaseType" />
                                                <v n="Value">"0"</v>
                                                <v n="DefaultValue">"0"</v>
                                              </o>
                                              <v n="Id">207L</v>
                                              <v n="IdParent">203L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">"P"</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">208L</v>
                                              <v n="IdParent">203L</v>
                                            </o>
                                          </l2>
                                          <v n="Id">203L</v>
                                          <v n="IdParent">26L</v>
                                        </o>
                                      </l2>
                                    </o>
                                    <l2 n="Attributes" cet="SFCAttribute">
                                      <o>
                                        <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">"Start_Pos"</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">27L</v>
                                        <v n="IdParent">26L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">"Skill"</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">28L</v>
                                        <v n="IdParent">26L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">29L</v>
                                        <v n="IdParent">26L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                        <o n="Value" t="EnumValue">
                                          <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                          <n n="BaseType" />
                                          <v n="Value">"0"</v>
                                          <v n="DefaultValue">"0"</v>
                                        </o>
                                        <v n="Id">30L</v>
                                        <v n="IdParent">26L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">31L</v>
                                        <v n="IdParent">26L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">32L</v>
                                        <v n="IdParent">26L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">33L</v>
                                        <v n="IdParent">26L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">34L</v>
                                        <v n="IdParent">26L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">35L</v>
                                        <v n="IdParent">26L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">36L</v>
                                        <v n="IdParent">26L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">37L</v>
                                        <v n="IdParent">26L</v>
                                      </o>
                                    </l2>
                                    <v n="Id">26L</v>
                                    <v n="IdParent">418L</v>
                                  </o>
                                </l2>
                              </o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">419L</v>
                                  <v n="IdParent">418L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">420L</v>
                                  <v n="IdParent">418L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">421L</v>
                                  <v n="IdParent">418L</v>
                                </o>
                              </l2>
                              <v n="Id">418L</v>
                              <v n="IdParent">413L</v>
                            </o>
                            <o>
                              <o n="ElementList" t="SFCElementList">
                                <l2 n="InnerList" cet="SFCStep">
                                  <o>
                                    <n n="EmbeddedMainAction" />
                                    <n n="EmbeddedEntryAction" />
                                    <n n="EmbeddedExitAction" />
                                    <l2 n="EmbeddedMainActionProperties" />
                                    <l2 n="EmbeddedEntryActionProperties" />
                                    <l2 n="EmbeddedExitActionProperties" />
                                    <o n="ElementList" t="SFCElementList">
                                      <l2 n="InnerList" cet="SFCActionAssociation">
                                        <o>
                                          <l2 n="Attributes" cet="SFCAttribute">
                                            <o>
                                              <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">"Z_Greif_Pos"</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">491L</v>
                                              <v n="IdParent">490L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">""</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">492L</v>
                                              <v n="IdParent">490L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                              <o n="Value" t="BoolValue">
                                                <v n="Value">"FALSE"</v>
                                                <v n="DefaultValue">"FALSE"</v>
                                              </o>
                                              <v n="Id">493L</v>
                                              <v n="IdParent">490L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                              <o n="Value" t="EnumValue">
                                                <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                                <n n="BaseType" />
                                                <v n="Value">"0"</v>
                                                <v n="DefaultValue">"0"</v>
                                              </o>
                                              <v n="Id">494L</v>
                                              <v n="IdParent">490L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">"N"</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">495L</v>
                                              <v n="IdParent">490L</v>
                                            </o>
                                          </l2>
                                          <v n="Id">490L</v>
                                          <v n="IdParent">433L</v>
                                        </o>
                                        <o>
                                          <l2 n="Attributes" cet="SFCAttribute">
                                            <o>
                                              <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">"Skill_G_P2P.M_Start"</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">497L</v>
                                              <v n="IdParent">496L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">""</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">498L</v>
                                              <v n="IdParent">496L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                              <o n="Value" t="BoolValue">
                                                <v n="Value">"FALSE"</v>
                                                <v n="DefaultValue">"FALSE"</v>
                                              </o>
                                              <v n="Id">499L</v>
                                              <v n="IdParent">496L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                              <o n="Value" t="EnumValue">
                                                <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                                <n n="BaseType" />
                                                <v n="Value">"0"</v>
                                                <v n="DefaultValue">"0"</v>
                                              </o>
                                              <v n="Id">500L</v>
                                              <v n="IdParent">496L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">"P"</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">501L</v>
                                              <v n="IdParent">496L</v>
                                            </o>
                                          </l2>
                                          <v n="Id">496L</v>
                                          <v n="IdParent">433L</v>
                                        </o>
                                      </l2>
                                    </o>
                                    <l2 n="Attributes" cet="SFCAttribute">
                                      <o>
                                        <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">"Greif_Pos"</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">434L</v>
                                        <v n="IdParent">433L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">"Skill"</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">435L</v>
                                        <v n="IdParent">433L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">436L</v>
                                        <v n="IdParent">433L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                        <o n="Value" t="EnumValue">
                                          <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                          <n n="BaseType" />
                                          <v n="Value">"0"</v>
                                          <v n="DefaultValue">"0"</v>
                                        </o>
                                        <v n="Id">437L</v>
                                        <v n="IdParent">433L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">438L</v>
                                        <v n="IdParent">433L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">439L</v>
                                        <v n="IdParent">433L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">440L</v>
                                        <v n="IdParent">433L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">441L</v>
                                        <v n="IdParent">433L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">442L</v>
                                        <v n="IdParent">433L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">443L</v>
                                        <v n="IdParent">433L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">"Reset_LGreiferVar"</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">444L</v>
                                        <v n="IdParent">433L</v>
                                      </o>
                                    </l2>
                                    <v n="Id">433L</v>
                                    <v n="IdParent">422L</v>
                                  </o>
                                </l2>
                              </o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">423L</v>
                                  <v n="IdParent">422L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">424L</v>
                                  <v n="IdParent">422L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">425L</v>
                                  <v n="IdParent">422L</v>
                                </o>
                              </l2>
                              <v n="Id">422L</v>
                              <v n="IdParent">413L</v>
                            </o>
                          </l2>
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">414L</v>
                            <v n="IdParent">413L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">415L</v>
                            <v n="IdParent">413L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">416L</v>
                            <v n="IdParent">413L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"TRUE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">417L</v>
                            <v n="IdParent">413L</v>
                          </o>
                        </l2>
                        <v n="Id">413L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Start_Pos__to__Offset_nZ"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Skill_R_P2P.P_State = 0 AND Skill_G_P2P.P_State = 0 AND Start_Pos.t &gt; T#0.2s"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">453L</v>
                            <v n="IdParent">452L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">454L</v>
                            <v n="IdParent">452L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">455L</v>
                            <v n="IdParent">452L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">456L</v>
                            <v n="IdParent">452L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">457L</v>
                            <v n="IdParent">452L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">458L</v>
                            <v n="IdParent">452L</v>
                          </o>
                        </l2>
                        <v n="Id">452L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" cet="SFCActionAssociation">
                            <o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"Z_Offset_nZ"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">528L</v>
                                  <v n="IdParent">527L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">529L</v>
                                  <v n="IdParent">527L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">530L</v>
                                  <v n="IdParent">527L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">531L</v>
                                  <v n="IdParent">527L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"N"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">532L</v>
                                  <v n="IdParent">527L</v>
                                </o>
                              </l2>
                              <v n="Id">527L</v>
                              <v n="IdParent">45L</v>
                            </o>
                            <o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"Skill_R_P2P.M_Start"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">522L</v>
                                  <v n="IdParent">521L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">523L</v>
                                  <v n="IdParent">521L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">524L</v>
                                  <v n="IdParent">521L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">525L</v>
                                  <v n="IdParent">521L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"P"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">526L</v>
                                  <v n="IdParent">521L</v>
                                </o>
                              </l2>
                              <v n="Id">521L</v>
                              <v n="IdParent">45L</v>
                            </o>
                          </l2>
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Offset_nZ"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">46L</v>
                            <v n="IdParent">45L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Skill"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">47L</v>
                            <v n="IdParent">45L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">48L</v>
                            <v n="IdParent">45L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">49L</v>
                            <v n="IdParent">45L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">50L</v>
                            <v n="IdParent">45L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">51L</v>
                            <v n="IdParent">45L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">52L</v>
                            <v n="IdParent">45L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">53L</v>
                            <v n="IdParent">45L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">54L</v>
                            <v n="IdParent">45L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">55L</v>
                            <v n="IdParent">45L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">56L</v>
                            <v n="IdParent">45L</v>
                          </o>
                        </l2>
                        <v n="Id">45L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Offset_nZ__to__Greifen"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Skill_R_P2P.P_State = 0 AND Start_Pos.t &gt; T#0.2s"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">122L</v>
                            <v n="IdParent">121L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">123L</v>
                            <v n="IdParent">121L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">124L</v>
                            <v n="IdParent">121L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">125L</v>
                            <v n="IdParent">121L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">126L</v>
                            <v n="IdParent">121L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">127L</v>
                            <v n="IdParent">121L</v>
                          </o>
                        </l2>
                        <v n="Id">121L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" cet="SFCActionAssociation">
                            <o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"Z_Greifen"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">553L</v>
                                  <v n="IdParent">552L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">554L</v>
                                  <v n="IdParent">552L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">555L</v>
                                  <v n="IdParent">552L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">556L</v>
                                  <v n="IdParent">552L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"N"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">557L</v>
                                  <v n="IdParent">552L</v>
                                </o>
                              </l2>
                              <v n="Id">552L</v>
                              <v n="IdParent">71L</v>
                            </o>
                            <o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"Skill_G_P2P.M_Start"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">559L</v>
                                  <v n="IdParent">558L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">560L</v>
                                  <v n="IdParent">558L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">561L</v>
                                  <v n="IdParent">558L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">562L</v>
                                  <v n="IdParent">558L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"P"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">563L</v>
                                  <v n="IdParent">558L</v>
                                </o>
                              </l2>
                              <v n="Id">558L</v>
                              <v n="IdParent">71L</v>
                            </o>
                          </l2>
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Greifen"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">72L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Skill"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">73L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">74L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">75L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">76L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">77L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">78L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">79L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">80L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">81L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Reset_LGreiferVar"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">82L</v>
                            <v n="IdParent">71L</v>
                          </o>
                        </l2>
                        <v n="Id">71L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Greifen__to__Offset_Z"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Skill_G_P2P.P_State = 0 AND Start_Pos.t &gt; T#0.2s"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">141L</v>
                            <v n="IdParent">140L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">142L</v>
                            <v n="IdParent">140L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">143L</v>
                            <v n="IdParent">140L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">144L</v>
                            <v n="IdParent">140L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">145L</v>
                            <v n="IdParent">140L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">146L</v>
                            <v n="IdParent">140L</v>
                          </o>
                        </l2>
                        <v n="Id">140L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" cet="SFCActionAssociation">
                            <o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"Z_Offset_Z"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">584L</v>
                                  <v n="IdParent">583L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">585L</v>
                                  <v n="IdParent">583L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">586L</v>
                                  <v n="IdParent">583L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">587L</v>
                                  <v n="IdParent">583L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"N"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">588L</v>
                                  <v n="IdParent">583L</v>
                                </o>
                              </l2>
                              <v n="Id">583L</v>
                              <v n="IdParent">90L</v>
                            </o>
                            <o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"Skill_R_P2P.M_Start"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">590L</v>
                                  <v n="IdParent">589L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">591L</v>
                                  <v n="IdParent">589L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">592L</v>
                                  <v n="IdParent">589L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">593L</v>
                                  <v n="IdParent">589L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"P"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">594L</v>
                                  <v n="IdParent">589L</v>
                                </o>
                              </l2>
                              <v n="Id">589L</v>
                              <v n="IdParent">90L</v>
                            </o>
                          </l2>
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Offset_Z"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">91L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Skill"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">92L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">93L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">94L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">95L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">96L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">97L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">98L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">99L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">100L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Reset_LRobotVar"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">101L</v>
                            <v n="IdParent">90L</v>
                          </o>
                        </l2>
                        <v n="Id">90L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Offset_Z__to__Finished"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Skill_R_P2P.P_State = 0 AND Start_Pos.t &gt; T#0.2s"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">160L</v>
                            <v n="IdParent">159L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">161L</v>
                            <v n="IdParent">159L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">162L</v>
                            <v n="IdParent">159L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">163L</v>
                            <v n="IdParent">159L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">164L</v>
                            <v n="IdParent">159L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">165L</v>
                            <v n="IdParent">159L</v>
                          </o>
                        </l2>
                        <v n="Id">159L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" cet="SFCActionAssociation">
                            <o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"M_Stop"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">249L</v>
                                  <v n="IdParent">248L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">250L</v>
                                  <v n="IdParent">248L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">251L</v>
                                  <v n="IdParent">248L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">252L</v>
                                  <v n="IdParent">248L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"P"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">253L</v>
                                  <v n="IdParent">248L</v>
                                </o>
                              </l2>
                              <v n="Id">248L</v>
                              <v n="IdParent">185L</v>
                            </o>
                          </l2>
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Finished"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">186L</v>
                            <v n="IdParent">185L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">187L</v>
                            <v n="IdParent">185L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">188L</v>
                            <v n="IdParent">185L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">189L</v>
                            <v n="IdParent">185L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">190L</v>
                            <v n="IdParent">185L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">191L</v>
                            <v n="IdParent">185L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">192L</v>
                            <v n="IdParent">185L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">193L</v>
                            <v n="IdParent">185L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">194L</v>
                            <v n="IdParent">185L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">195L</v>
                            <v n="IdParent">185L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">196L</v>
                            <v n="IdParent">185L</v>
                          </o>
                        </l2>
                        <v n="Id">185L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Finished__to__Init"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"bBeendet"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">58L</v>
                            <v n="IdParent">57L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">59L</v>
                            <v n="IdParent">57L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">60L</v>
                            <v n="IdParent">57L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">61L</v>
                            <v n="IdParent">57L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">62L</v>
                            <v n="IdParent">57L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">63L</v>
                            <v n="IdParent">57L</v>
                          </o>
                        </l2>
                        <v n="Id">57L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCJump">
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Init"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">23L</v>
                            <v n="IdParent">22L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">24L</v>
                            <v n="IdParent">22L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">25L</v>
                            <v n="IdParent">22L</v>
                          </o>
                        </l2>
                        <v n="Id">22L</v>
                        <v n="IdParent">2L</v>
                      </o>
                    </l2>
                  </o>
                  <l2 n="Attributes" cet="SFCAttribute">
                    <o>
                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                      <o n="Value" t="StringValue">
                        <v n="Value">""</v>
                        <v n="DefaultValue">""</v>
                      </o>
                      <v n="Id">245L</v>
                      <v n="IdParent">2L</v>
                    </o>
                    <o>
                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                      <o n="Value" t="StringValue">
                        <v n="Value">""</v>
                        <v n="DefaultValue">""</v>
                      </o>
                      <v n="Id">246L</v>
                      <v n="IdParent">2L</v>
                    </o>
                    <o>
                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                      <o n="Value" t="BoolValue">
                        <v n="Value">"FALSE"</v>
                        <v n="DefaultValue">"FALSE"</v>
                      </o>
                      <v n="Id">247L</v>
                      <v n="IdParent">2L</v>
                    </o>
                  </l2>
                  <v n="Id">2L</v>
                  <v n="IdParent">-1L</v>
                </o>
                <d2 n="Categories" ckt="Guid" cvt="SFCAttributeCategory">
                  <v>1c5c6e05-2bb7-4258-bcee-fd16a540c63c</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Identifier">"Specific"</v>
                    <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                    <v n="Description">"Element type specific properties"</v>
                  </o>
                  <v>20f0fc67-978d-438b-979f-eef294f34ee4</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Identifier">"Actions"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Action definitions"</v>
                  </o>
                  <v>6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Identifier">"Common"</v>
                    <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                    <v n="Description">"Common properties"</v>
                  </o>
                  <v>d336ba06-8a67-4e6b-9697-50f83ba6bdde</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                    <v n="Identifier">"Times"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Time definitions"</v>
                  </o>
                </d2>
                <d2 n="Attributes" ckt="Guid" cvt="SFCAttributeDescription">
                  <v>01580b27-6378-448b-8ecb-0e4b795b58d6</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">true</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                    <v n="Identifier">"Exclude"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Exclude this element from build"</v>
                  </o>
                  <v>23bdaa98-72ec-41f7-817b-9dede5697086</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                    <v n="Identifier">"Parallel"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Sets the branch to parallel mode"</v>
                  </o>
                  <v>38391c6d-6d4a-42f8-8ee7-9f45e5adafa8</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                    <v n="Identifier">"Name"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Name of the element"</v>
                  </o>
                  <v>62e1754b-7629-4e63-9cec-10ae0c536f1f</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                    <v n="Identifier">"Duplication"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Copies the implementation of step actions or transitions with the element. Otherwise, copies the reference to an existing implementation."</v>
                  </o>
                  <v>6844a48e-46c2-4cc8-a185-a478f3b99cc0</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                    <v n="Identifier">"InitStep"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Sets the step as the initial step"</v>
                  </o>
                  <v>700a583f-b4d4-43e4-8c14-629c7cd3bec8</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                    <v n="Identifier">"MainAction"</v>
                    <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Description">"Name of the action to be called if the step is active"</v>
                  </o>
                  <v>7d894980-aeea-405c-a0f6-e2b26429c58f</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">true</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                    <v n="Identifier">"Comment"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Comment of the element"</v>
                  </o>
                  <v>8294df19-5962-4dee-a874-1051dabb0e3e</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                    <v n="Identifier">"Monitoring"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Indicates transition monitoring setting."</v>
                  </o>
                  <v>a2621e18-7de3-4ea6-ae6d-89e9e0b7befd</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                    <v n="Identifier">"ExitAction"</v>
                    <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Description">"Name of the action to be called if the step is deactivated"</v>
                  </o>
                  <v>a6b08bd8-b696-47e3-9cbf-7408b61c9ff8</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                    <v n="Identifier">"EntryAction"</v>
                    <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Description">"Name of the action to be called if the step is activated"</v>
                  </o>
                  <v>b693554c-1b01-4a8d-afde-9e3a46f7465d</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                    <v n="Identifier">"MaxTime"</v>
                    <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                    <v n="Description">"Defines the maximal active time for the step"</v>
                  </o>
                  <v>bc882c11-1e91-4dd8-a6b8-2075724ed18b</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                    <v n="Identifier">"Symbol"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Symbol configuration setting of the element"</v>
                  </o>
                  <v>cacf1a68-236e-47c2-b7b1-1cf9199718cb</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                    <v n="Identifier">"MinTime"</v>
                    <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                    <v n="Description">"Defines the minimal active time for the step"</v>
                  </o>
                  <v>e174fc0d-80b0-4a9e-a530-ca239c249a50</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                    <v n="Identifier">"Qualifier"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Qualifier of the action association"</v>
                  </o>
                </d2>
                <d2 n="EnumTemplates" ckt="Guid" cvt="EnumValueTemplate">
                  <v>6ecff51c-9b8f-4338-aab0-67c2b31b07e9</v>
                  <o>
                    <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                    <l n="Values" t="ArrayList" cet="EnumEntry">
                      <o>
                        <v n="Identifier">"None"</v>
                        <v n="Value">0L</v>
                        <v n="Key">"None"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Variable"</v>
                        <v n="Value">1L</v>
                        <v n="Key">"Variable"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Call"</v>
                        <v n="Value">2L</v>
                        <v n="Key">"Call"</v>
                      </o>
                    </l>
                    <v n="BaseType">"INT"</v>
                  </o>
                  <v>79a4fdd5-c859-4de4-aa8d-c03372c880c2</v>
                  <o>
                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                    <l n="Values" t="ArrayList" cet="EnumEntry">
                      <o>
                        <v n="Identifier">"Unspecified"</v>
                        <v n="Value">0L</v>
                        <v n="Key">"Unspecified"</v>
                      </o>
                      <o>
                        <v n="Identifier">"None"</v>
                        <v n="Value">1L</v>
                        <v n="Key">"None"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Read"</v>
                        <v n="Value">2L</v>
                        <v n="Key">"Read"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Write"</v>
                        <v n="Value">3L</v>
                        <v n="Key">"Write"</v>
                      </o>
                      <o>
                        <v n="Identifier">"ReadWrite"</v>
                        <v n="Value">4L</v>
                        <v n="Key">"ReadWrite"</v>
                      </o>
                    </l>
                    <v n="BaseType">"INT"</v>
                  </o>
                </d2>
                <v n="ImplId">1L</v>
              </o>
            </Data>
            <TypeList>
              <Type n="ArrayList">System.Collections.ArrayList</Type>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="BoolValue">{89e1c7bb-c9f8-4be3-b8a7-019cdbb9f7e8}</Type>
              <Type n="EnumEntry">{4185e6da-1717-44c9-b705-102861764479}</Type>
              <Type n="EnumValue">{4dd7572b-4b9d-4d35-963e-6a34a4aaa5c1}</Type>
              <Type n="EnumValueTemplate">{d6bfe4f0-d62f-4b5f-9f95-2bbeb1950e28}</Type>
              <Type n="Guid">System.Guid</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="SFCActionAssociation">{a94bb75d-5fb3-40ad-9d01-41d5b980784d}</Type>
              <Type n="SFCAttribute">{21f3f16e-04fa-4637-b6b7-d84e4192e99f}</Type>
              <Type n="SFCAttributeCategory">{679adacf-f2a4-4167-a3f7-d21cfc5d451f}</Type>
              <Type n="SFCAttributeDescription">{d851789d-af2c-4990-9d48-a7bdc9181773}</Type>
              <Type n="SFCBranch">{e221b778-bb8f-44ba-8a6a-f796287d4e62}</Type>
              <Type n="SFCElementList">{587d6556-cfe6-4e76-9cc9-fc0daf0c8c29}</Type>
              <Type n="SFCImplementationObject">{74f81948-1328-492c-b6c1-a9ea72048b28}</Type>
              <Type n="SFCJump">{7e39ac27-154f-419a-a255-6a6cf37d5ed0}</Type>
              <Type n="SFCSegment">{f1db7f6f-4774-46a6-ad9b-a94414f875fc}</Type>
              <Type n="SFCStep">{86ee92a2-d863-4136-be27-82b36d84211c}</Type>
              <Type n="SFCTransition">{4ecb29e8-a90a-4646-84ac-2ff54215ab29}</Type>
              <Type n="String">System.String</Type>
              <Type n="StringValue">{778c8bac-3fa0-41e1-99d3-2b628d12d3e5}</Type>
            </TypeList>
          </XmlArchive>
        </SFC>
      </Implementation>
      <ObjectProperties>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="SFCProperty">
              <n n="SFCErrorAnalyzation" />
              <n n="SFCErrorAnalyzationTable" />
              <n n="SFCCurrentSteps" />
              <n n="SFCMetaSteps" />
              <v n="Title">"IecSfc"</v>
              <v n="Company">"System"</v>
              <v n="Version">"4.4.0.0"</v>
              <v n="Namespace">""</v>
              <d2 n="Flags" ckt="Flags" cvt="SFCPropertyFlagData">
                <v>EnableLimit</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Init</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Reset</v>
                <o>
                  <v n="Use">true</v>
                  <v n="Declare">true</v>
                </o>
                <v>QuitError</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Pause</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Error</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Trans</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>ErrorStep</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>ErrorPOU</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>CurrentStep</v>
                <o>
                  <v n="Use">true</v>
                  <v n="Declare">true</v>
                </o>
                <v>Tip</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>TipMode</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>SFCErrorAnalyzation</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>SFCErrorAnalyzationTable</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>CurrentSteps</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>MetaSteps</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">false</v>
                </o>
              </d2>
              <v n="CalcActiveTransOnly">true</v>
              <v n="UseDefaults">false</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="Flags">{27d8150b-ef58-4fff-8da1-1f7dd5f9ea51}</Type>
            <Type n="SFCProperty">{58548d2c-f1b1-453d-9195-66c94e2a3ae0}</Type>
            <Type n="SFCPropertyFlagData">{24565a38-6368-4874-ab9a-0ef7ec269521}</Type>
            <Type n="String">System.String</Type>
          </TypeList>
        </XmlArchive>
      </ObjectProperties>
    </Action>
    <Action Name="Reset_LGreiferVar" Id="{9d3ba51b-68db-4969-b0ec-bd6026784695}" FolderPath="00_Resetten\">
      <Implementation>
        <ST><![CDATA[LGreiferVar.F := 0;
LGreiferVar.Geschw := 0;
LGreiferVar.Pos := 0;		
]]></ST>
      </Implementation>
    </Action>
    <Action Name="Reset_LRobotVar" Id="{c7d610f8-338a-4f70-9eb5-d7188d3de136}" FolderPath="00_Resetten\">
      <Implementation>
        <ST><![CDATA[LRobotVar.q1 := 0;
LRobotVar.q2 := 0;
LRobotVar.q3 := 0;
LRobotVar.q4 := 0;
LRobotVar.q5 := 0;
LRobotVar.q6 := 0;
LRobotVar.v := 0;
LRobotVar.a := 0;
LRobotVar.MoveTyp := 0;
LRobotVar.PosTyp := 0;]]></ST>
      </Implementation>
    </Action>
    <Action Name="Z_Greif_Pos" Id="{d3fef3d4-c96d-45ae-8528-42d88906181b}" FolderPath="01_Zuweisung\">
      <Implementation>
        <ST><![CDATA[// Skillaufruf
Skill_G_P2P(eSysCommand := GVL.SystemCommand,
			eSysState := GVL.SystemState,
			Objekt := I_Greifer,
			iErrorID => GVL.ErrorID);
			
// Parameterbestimmung
LGreiferVar.F := 100;
LGreiferVar.Geschw := 100;
LGreiferVar.Pos := Param_Backenbreite;		

// Parameterzuweisung
Skill_G_P2P.P_SGripperParam := LGreiferVar;]]></ST>
      </Implementation>
    </Action>
    <Action Name="Z_Greifen" Id="{f39cddff-5c7f-43c2-a680-68cd117303fb}" FolderPath="01_Zuweisung\">
      <Implementation>
        <ST><![CDATA[// Skillaufruf
Skill_G_P2P(eSysCommand := GVL.SystemCommand,
			eSysState := GVL.SystemState,
			Objekt := I_Greifer,
			iErrorID => GVL.ErrorID);
			
// Parameterbestimmung
LGreiferVar.F := 50;
LGreiferVar.Geschw := 50;
LGreiferVar.Pos := 10;		

// Parameterzuweisung
Skill_G_P2P.P_SGripperParam := LGreiferVar;]]></ST>
      </Implementation>
    </Action>
    <Action Name="Z_Home_Position_" Id="{1c550bea-b9ce-4791-b09b-797d27b9f5fa}" FolderPath="01_Zuweisung\">
      <Implementation>
        <ST><![CDATA[// Skillaufruf
Skill_R_P2P(eSysCommand := GVL.SystemCommand,
			eSysState := GVL.SystemState,
			Objekt := I_Roboter,
			iErrorID => GVL.ErrorID);


// Parameterbestimmung			
LRobotVar := PunkteZuweisung_Temp.PHome;
		
// Parameterzuweisung	
Skill_R_P2P.P_RobotParam := LRobotVar;]]></ST>
      </Implementation>
    </Action>
    <Action Name="Z_Offset_nZ" Id="{e1dacfae-3213-452a-9198-1f4a435392ac}" FolderPath="01_Zuweisung\">
      <Implementation>
        <ST><![CDATA[// Skillaufruf
Skill_R_P2P(eSysCommand := GVL.SystemCommand,
			eSysState := GVL.SystemState,
			Objekt := I_Roboter,
			iErrorID => GVL.ErrorID);

// Parameterbestimmung			
LRobotVar.q1 := 0;
LRobotVar.q2 := 0;
LRobotVar.q3 := -0.03;
LRobotVar.q4 := 0;
LRobotVar.q5 := 0;
LRobotVar.q6 := 0;
LRobotVar.v := 0.1;
LRobotVar.a := 0.1;
LRobotVar.MoveTyp := 0;
LRobotVar.PosTyp := 1;

// Parameterzuweisung	
Skill_R_P2P.P_RobotParam := LRobotVar;]]></ST>
      </Implementation>
    </Action>
    <Action Name="Z_Offset_Z" Id="{1879a83e-38ba-480f-9ce5-5bc8580a54f5}" FolderPath="01_Zuweisung\">
      <Implementation>
        <ST><![CDATA[// Skillaufruf
Skill_R_P2P(eSysCommand := GVL.SystemCommand,
			eSysState := GVL.SystemState,
			Objekt := I_Roboter,
			iErrorID => GVL.ErrorID);

// Parameterbestimmung			
LRobotVar.q1 := 0;
LRobotVar.q2 := 0;
LRobotVar.q3 := 0.03;
LRobotVar.q4 := 0;
LRobotVar.q5 := 0;
LRobotVar.q6 := 0;
LRobotVar.v := 0.1;
LRobotVar.a := 0.1;
LRobotVar.MoveTyp := 0;
LRobotVar.PosTyp := 1;
		
// Parameterzuweisung	
Skill_R_P2P.P_RobotParam := LRobotVar;]]></ST>
      </Implementation>
    </Action>
    <Action Name="Z_Start_Pos" Id="{60a67d5d-5211-40e2-bdcc-18dbb6c3cfcb}" FolderPath="01_Zuweisung\">
      <Implementation>
        <ST><![CDATA[
// Skillaufruf
Skill_R_P2P(eSysCommand := GVL.SystemCommand,
			eSysState := GVL.SystemState,
			Objekt := I_Roboter,
			iErrorID => GVL.ErrorID);

// Parameterbestimmung			
LRobotVar := Param_StartPos;
		
// Parameterzuweisung	
Skill_R_P2P.P_RobotParam := LRobotVar;



]]></ST>
      </Implementation>
    </Action>
  </POU>
</TcPlcObject>