<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{df9a06fb-c7f6-44ef-905d-60a2bbb547dc}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Position_1		:sRoboterProzessVariablen;
	Position_2		:sRoboterProzessVariablen;
	GreifPos_1		:sSmartGreiferProzessVariablen;
	GreifPos_2		:sSmartGreiferProzessVariablen;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Aufrufen der Objekte
Anlage();
// Aufrufen der Skills
SkillSet();
// Aufrufen der Systenparameterzuweisung 
Systemparameter();
// Aufrunfen des Zustandshandlings
Zustandshandling();
// Temporäre Punktedatenbank
PunkteZuweisung_Temp();

// Aufrufen von Testablauf
AP_1();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>