<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_SequenzReferenz" Id="{6b767d26-9b1c-4026-9e95-eab42be9026d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SequenzReferenz IMPLEMENTS I_Sequenz
VAR_INPUT
	// Betriebsvariablen
	
	
	// Benötigter Skill
	
	// Benötigte Parameter
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="M_Start" Id="{eb3028dc-dbec-4628-90f5-df6c4d441337}">
      <Declaration><![CDATA[METHOD M_Start : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Stop" Id="{7827b4f4-2c1e-4275-b842-f33cf6f9db3e}">
      <Declaration><![CDATA[METHOD M_Stop : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="P_State" Id="{7c2827b6-3c77-441b-a023-4c1a9cbde076}">
      <Declaration><![CDATA[PROPERTY P_State : eSequenceState]]></Declaration>
      <Get Name="Get" Id="{deb48184-48ba-4b82-9206-4b1433cba5a7}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>