<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="GrundstrukturSkill" Id="{8849c73d-5d94-464c-8fa0-5cada18e040f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK GrundstrukturSkill IMPLEMENTS I_State_Skill
VAR_INPUT
	bExecute			:BOOL;				// Trigger für Ausführung von Skill
	bReset				:BOOL;				// Trigger für Reset von Skill
	iObjState			:eObjectState;		// Information über Zustand von Objekt
	iSysState			:eSystemState;		// Information über Zustand von System
END_VAR
VAR_OUTPUT
	iSkillCommand		:eSkillCommand;		// Steuerungsvariable für Anlagenmodell
	bDone				:BOOL;				// Information ob Skill ausgfeührt wurde
	bBusy				:BOOL;				// Information ob Skill im Moment ausgeführt wird
	bLimit				:BOOL;				// Information ob Skill an einem Limit angekommen ist
	bError				:BOOL;				// Information ob sich Skill in Fehlerzustand befindet
	iErrorID			:INT;				// Information um welchen Fehler es sich handelt
END_VAR
VAR
	iState				:eSkillState;		// Information über Zustand von Skill
	bTargetReached		:BOOL;				// Information ob Prozessziel erreicht wurde
	bLimitReached		:BOOL;				// Information ob Limit erreicht wurde
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="P_State" Id="{174b5214-bae6-4f3c-b2eb-b050fc2deeb8}">
      <Declaration><![CDATA[PROPERTY P_State : eSkillState]]></Declaration>
      <Get Name="Get" Id="{611af6d0-4b12-4b33-98af-b90cc15ee0fa}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[P_State := iState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>